### ISSUE TITLE
[ERROR] cannot visit harbor UI, contanier harbor-db restarting.

### ISSUE THREAD

**Issue by lmsreborn** [vmware/harbor#1354]
1. docker-compose version 1.10, docker version 1.13.1
2. The container harbor-db is always restarting. The logs in `/var/log/harbor/2017-02-13/ui.log` : 
```Feb 13 02:44:02 172.18.0.1 ui[8918]: panic: failed to connect to database after 60 seconds
Feb 13 02:44:02 172.18.0.1 ui[8918]:
Feb 13 02:44:02 172.18.0.1 ui[8918]: goroutine 1 [running]:
Feb 13 02:44:02 172.18.0.1 ui[8918]: panic(0xbdb780, 0xc820329a10)
Feb 13 02:44:02 172.18.0.1 ui[8918]: #011/usr/local/go/src/runtime/panic.go:481 +0x3e6
Feb 13 02:44:02 172.18.0.1 ui[8918]: github.com/vmware/harbor/src/common/dao.InitDatabase()
Feb 13 02:44:02 172.18.0.1 ui[8918]: #011/go/src/github.com/vmware/harbor/src/common/dao/base.go:50 +0x1d7
Feb 13 02:44:02 172.18.0.1 ui[8918]: main.main()
Feb 13 02:44:02 172.18.0.1 ui[8918]: #011/go/src/github.com/vmware/harbor/src/ui/main.go:78 +0xd8
Feb 13 02:44:03 172.18.0.1 ui[8918]: 2017-02-13T02:44:03Z [INFO] token expiration: 30 minutes
Feb 13 02:44:03 172.18.0.1 ui[8918]: 2017-02-13T02:44:03Z [INFO] Config path: /etc/ui/app.conf
Feb 13 02:44:03 172.18.0.1 ui[8918]: 2017-02-13T02:44:03Z [INFO] initializing database: type-MySQL host-mysql port-3306 user-root database-registry
Feb 13 02:44:03 172.18.0.1 ui[8918]: 2017-02-13T02:44:03Z [ERROR] [mysql.go:79]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
Feb 13 02:44:05 172.18.0.1 ui[8918]: 2017-02-13T02:44:05Z [ERROR] [mysql.go:79]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
~```
It means that mysql is not working well, and it cannot find the host mysql. Can anyone help slove the problem?

**Comment by lmsreborn** [comment]
Oh, I've fixed this problem. The log in `/var/log/harbor/mysql.log/2017-02-13/mysql.log` tells me that the problem is that my memory is too small to allocate something.

**Comment by reasonerjt** [comment]
Thanks for the update, closing the issue.
