### ISSUE TITLE
the yam file  can not work on kubernetes v1.7.0

### ISSUE THREAD

**Issue by justlooks** [vmware/harbor#2881]
Environment:

<b>Kubernetes version (use kubectl version): v1.7.0
Cloud provider or hardware configuration**:
OS (e.g. from /etc/os-release): CentOS 7
Kernel (e.g. uname -a): Linux k8s-master 3.10.0-514.6.2.el7.x86_64
Install tools: Kubeadm
Others:
docker version : Docker version 1.12.6,
My RPM version :
docker-1.12.6-16.el7.centos.x86_64.rpm
kubectl-1.7.0-0.x86_64.rpm
kubernetes-cni-0.5.1-0.x86_64.rpm
kubeadm-1.7.0-0.x86_64.rpm
kubelet-1.7.0-0.x86_64.rpm</b>

i follow the document https://github.com/vmware/harbor/blob/release-1.1.0/docs/kubernetes_deployment.md ,the observer ,nginx, ui pod crash .

```
[root@k8s-master ui]# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                    READY     STATUS             RESTARTS   AGE       IP              NODE
default       busybox                                 1/1       Running            45         1d        172.16.1.98     k8s-node1
default       jobservice-rc-htjrc                     0/1       CrashLoopBackOff   5          11m       172.16.2.9      k8s-node2
default       mysql-rc-q67xx                          1/1       Running            0          11m       172.16.1.104    k8s-node1
default       nginx-rc-6v2gr                          0/1       CrashLoopBackOff   7          11m       172.16.2.10     k8s-node2
default       registry-rc-v1n0h                       0/1       Error              7          11m       172.16.1.103    k8s-node1
default       ui-rc-d9qs6                             0/1       CrashLoopBackOff   5          11m       172.16.1.105    k8s-node1
kube-system   etcd-k8s-master                         1/1       Running            1          1d        10.132.41.234   k8s-master
kube-system   heapster-2994581613-cx1r7               1/1       Running            0          1d        172.16.2.8      k8s-node2
kube-system   kube-apiserver-k8s-master               1/1       Running            1          1d        10.132.41.234   k8s-master
kube-system   kube-controller-manager-k8s-master      1/1       Running            4          1d        10.132.41.234   k8s-master
kube-system   kube-dns-2425271678-4ck8r               3/3       Running            3          1d        172.16.0.74     k8s-master
kube-system   kube-flannel-ds-f67j6                   2/2       Running            0          1d        10.161.233.80   k8s-node2
kube-system   kube-flannel-ds-j936w                   2/2       Running            2          1d        10.132.41.234   k8s-master
kube-system   kube-flannel-ds-n36wb                   2/2       Running            0          1d        10.165.97.219   k8s-node1
kube-system   kube-proxy-3nspx                        1/1       Running            0          1d        10.161.233.80   k8s-node2
kube-system   kube-proxy-gsr5t                        1/1       Running            1          1d        10.132.41.234   k8s-master
kube-system   kube-proxy-zqg7j                        1/1       Running            0          1d        10.165.97.219   k8s-node1
kube-system   kube-scheduler-k8s-master               1/1       Running            3          1d        10.132.41.234   k8s-master
kube-system   kubernetes-dashboard-2209332821-k9wwf   1/1       Running            0          1d        172.16.2.2      k8s-node2
kube-system   monitoring-grafana-1850655027-rj868     1/1       Running            0          1d        172.16.2.7      k8s-node2
kube-system   monitoring-influxdb-1870447071-rvqr5    1/1       Running            0          1d        172.16.1.101    k8s-node1
```

/sig bug

**Comment by justlooks** [comment]
i change "ui_url_protocol = http" in harbor.cfg to "ui_url_protocol = https",now nginx start work,but registry still crash

```
[root@k8s-master harbor]# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                    READY     STATUS             RESTARTS   AGE       IP              NODE
default       busybox                                 1/1       Running            48         2d        172.16.1.98     k8s-node1
default       jobservice-rc-pm6sx                     1/1       Running            2          3m        172.16.2.11     k8s-node2
default       mysql-rc-q67xx                          1/1       Running            0          2h        172.16.1.104    k8s-node1
default       nginx-rc-6v2gr                          1/1       Running            39         2h        172.16.2.10     k8s-node2
default       registry-rc-43b92                       0/1       CrashLoopBackOff   5          3m        172.16.1.106    k8s-node1
default       ui-rc-mx8nq                             1/1       Running            2          3m        172.16.1.107    k8s-node1
kube-system   etcd-k8s-master                         1/1       Running            1          2d        10.132.41.234   k8s-master
kube-system   heapster-2994581613-cx1r7               1/1       Running            0          1d        172.16.2.8      k8s-node2
kube-system   kube-apiserver-k8s-master               1/1       Running            1          2d        10.132.41.234   k8s-master
kube-system   kube-controller-manager-k8s-master      1/1       Running            4          2d        10.132.41.234   k8s-master
kube-system   kube-dns-2425271678-4ck8r               3/3       Running            3          2d        172.16.0.74     k8s-master
kube-system   kube-flannel-ds-f67j6                   2/2       Running            0          2d        10.161.233.80   k8s-node2
kube-system   kube-flannel-ds-j936w                   2/2       Running            2          2d        10.132.41.234   k8s-master
kube-system   kube-flannel-ds-n36wb                   2/2       Running            0          2d        10.165.97.219   k8s-node1
kube-system   kube-proxy-3nspx                        1/1       Running            0          2d        10.161.233.80   k8s-node2
kube-system   kube-proxy-gsr5t                        1/1       Running            1          2d        10.132.41.234   k8s-master
kube-system   kube-proxy-zqg7j                        1/1       Running            0          2d        10.165.97.219   k8s-node1
kube-system   kube-scheduler-k8s-master               1/1       Running            3          2d        10.132.41.234   k8s-master
kube-system   kubernetes-dashboard-2209332821-k9wwf   1/1       Running            0          2d        172.16.2.2      k8s-node2
kube-system   monitoring-grafana-1850655027-rj868     1/1       Running            0          1d        172.16.2.7      k8s-node2
kube-system   monitoring-influxdb-1870447071-rvqr5    1/1       Running            0          1d        172.16.1.101    k8s-node1

[root@k8s-master harbor]# kubectl logs registry-rc-43b92
time="2017-07-27T06:00:08Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT"
time="2017-07-27T06:00:08Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5000_TCP"
time="2017-07-27T06:00:08Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5000_TCP_ADDR"
time="2017-07-27T06:00:08Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5000_TCP_PORT"
time="2017-07-27T06:00:08Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5000_TCP_PROTO"
time="2017-07-27T06:00:08Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5001_TCP"
time="2017-07-27T06:00:08Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5001_TCP_ADDR"
time="2017-07-27T06:00:08Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5001_TCP_PORT"
time="2017-07-27T06:00:08Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5001_TCP_PROTO"
time="2017-07-27T06:00:08Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_SERVICE_HOST"
time="2017-07-27T06:00:08Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_SERVICE_PORT"
time="2017-07-27T06:00:08Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_SERVICE_PORT_DEBUG"
time="2017-07-27T06:00:08Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_SERVICE_PORT_REPO"
time="2017-07-27T06:00:08.16277346Z" level=info msg="configuring endpoint harbor (http://ui/service/notifications), timeout=3s, headers=map[]" go.version=go1.7.5 instance.id=c1921172-d013-4a78-9270-4484848ade0f service=registry version=v2.6.1
time="2017-07-27T06:00:08.162859847Z" level=info msg="redis not configured" go.version=go1.7.5 instance.id=c1921172-d013-4a78-9270-4484848ade0f service=registry version=v2.6.1
time="2017-07-27T06:00:08.165864679Z" level=info msg="debug server listening localhost:5001"
time="2017-07-27T06:00:08.197203282Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.7.5 instance.id=c1921172-d013-4a78-9270-4484848ade0f service=registry version=v2.6.1
panic: unable to configure authorization (token): token auth requires at least one token signing root certificate
goroutine 1 [running]:
panic(0xb4cd00, 0xc4203a8110)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/docker/distribution/registry/handlers.NewApp(0x10667e0, 0xc4203737d0, 0xc42038e380, 0x10667e0)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:302 +0x1b6a
github.com/docker/distribution/registry.NewRegistry(0x7fb7a99d0068, 0xc4203737d0, 0xc42038e380, 0xe, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/registry.go:86 +0x213
github.com/docker/distribution/registry.glob..func1(0x108e160, 0xc420341450, 0x1, 0x1)
	/go/src/github.com/docker/distribution/registry/registry.go:55 +0x106
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x108e160, 0xc420341400, 0x1, 0x1, 0x108e160, 0xc420341400)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x190
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x108e300, 0xc4201dbf40, 0xc4200001a0)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x3c3
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:24 +0x2d

```
