### ISSUE TITLE
harbor 1.2.0rc1 fails to install on both rhel 7.3 and 7.4

### ISSUE THREAD

**Issue by choman** [vmware/harbor#3090]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.

    rhel 7.4
    Docker version 17.06.1-ce, build 874a737
    docker-compose version 1.9.0dev, build f5ad3e7
    harbor 1.2.0rc1

2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
located at: https://gist.github.com/8f6be32e626e6e59c4a430eb98f492f3

3)Log files, you can get them by package the /var/log/harbor/ .
located at: https://gist.github.com/828d362973e1b791c0c8f8512b08fbb9

Clearing the configuration file: ./common/config/nginx/cert/local.net.key
Clearing the configuration file: ./common/config/nginx/cert/local.net.crt
Clearing the configuration file: ./common/config/nginx/nginx.conf
Clearing the configuration file: ./common/config/adminserver/env
Clearing the configuration file: ./common/config/ui/env
Clearing the configuration file: ./common/config/registry/config.yml
Clearing the configuration file: ./common/config/db/env
Clearing the configuration file: ./common/config/jobservice/env
Generated and saved secret to file: /data/secretkey
Generated configuration file: ./common/config/nginx/nginx.conf
Generated configuration file: ./common/config/adminserver/env
Generated configuration file: ./common/config/ui/env
Generated configuration file: ./common/config/registry/config.yml
Generated configuration file: ./common/config/db/env
Generated configuration file: ./common/config/jobservice/env
Generated configuration file: ./common/config/jobservice/app.conf
Traceback (most recent call last):
  File "./prepare", line 254, in <module>
    shutil.copyfile(os.path.join(templates_dir, "jobservice", "app.conf"), jobservice_conf)
  File "/usr/lib64/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 21] Is a directory: u'./common/config/jobservice/app.conf'

**Comment by choman** [comment]
somehow these became directories:
Generated configuration file: ./common/config/jobservice/app.conf
Generated configuration file: ./common/config/ui/app.conf


Now failing here
Generated and saved secret to file: /data/secretkey
Generated configuration file: ./common/config/nginx/nginx.conf
Generated configuration file: ./common/config/adminserver/env
Generated configuration file: ./common/config/ui/env
Generated configuration file: ./common/config/registry/config.yml
Generated configuration file: ./common/config/db/env
Generated configuration file: ./common/config/jobservice/env
Generated configuration file: ./common/config/jobservice/app.conf
Generated configuration file: ./common/config/ui/app.conf
Fail to generate key file: ./common/config/ui/private_key.pem, cert file: ./common/config/registry/root.crt

**Comment by choman** [comment]
Looks like another weird directory happened
./common/config/ui/private_key.pem/

removed it and now insatllings
