### ISSUE TITLE
cI issue in pexpect

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#3209]
A few builds, such as https://ci.vcna.io/vmware/harbor/683
 fail at the some point:

```
Traceback (most recent call last):
3417s
472
  File "./tests/robot-cases/Group9-Content-trust/notary-push-image.py", line 27, in <module>
3417s
473
    child.expect(pexpect.EOF)
3417s
474
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 321, in expect
3417s
475
    timeout, searchwindowsize, async)
3417s
476
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 345, in expect_list
3417s
477
    return exp.expect_loop(timeout)
3417s
478
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 107, in expect_loop
3417s
479
    return self.timeout(e)
3417s
480
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 70, in timeout
3417s
481
    raise TIMEOUT(msg)
3417s
482
pexpect.exceptions.TIMEOUT: Timeout exceeded.
3417s
483
<pexpect.pty_spawn.spawn object at 0x7fc00fcb13d0>
```

Looks like the pattern in pexpect is not accurate.

**Comment by reasonerjt** [comment]
fixed in upstream
