### ISSUE TITLE
Deployment on K8S: registry   configuring endpoint harbor (http://ui/service/notifications) error

### ISSUE THREAD

**Issue by lixwlixw** [vmware/harbor#3265]
#default config run harbor on kubernetes  
#https://github.com/vmware/harbor/tree/master/make/kubernetes
#registry   error

time="2017-09-21T05:23:55Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT" 
time="2017-09-21T05:23:55Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5000_TCP" 
time="2017-09-21T05:23:55Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5000_TCP_ADDR" 
time="2017-09-21T05:23:55Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5000_TCP_PORT" 
time="2017-09-21T05:23:55Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5000_TCP_PROTO" 
time="2017-09-21T05:23:55Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5001_TCP" 
time="2017-09-21T05:23:55Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5001_TCP_ADDR" 
time="2017-09-21T05:23:55Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5001_TCP_PORT" 
time="2017-09-21T05:23:55Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5001_TCP_PROTO" 
time="2017-09-21T05:23:55Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_SERVICE_HOST" 
time="2017-09-21T05:23:55Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_SERVICE_PORT" 
time="2017-09-21T05:23:55Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_SERVICE_PORT_DEBUG" 
time="2017-09-21T05:23:55Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_SERVICE_PORT_REPO" 
time="2017-09-21T05:23:55.410333505Z" level=info msg="debug server listening localhost:5001" 
time="2017-09-21T05:23:55.411358063Z" level=info msg="configuring endpoint harbor (http://ui/service/notifications), timeout=3s, headers=map[]" go.version=go1.7.3 instance.id=1ded5ca7-45c3-49bd-bde8-6dd6f64c2f36 service=registry version=v2.6.2 
time="2017-09-21T05:23:55.411426181Z" level=info msg="redis not configured" go.version=go1.7.3 instance.id=1ded5ca7-45c3-49bd-bde8-6dd6f64c2f36 service=registry version=v2.6.2 
time="2017-09-21T05:23:55.444089449Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.7.3 instance.id=1ded5ca7-45c3-49bd-bde8-6dd6f64c2f36 service=registry version=v2.6.2 
panic: unable to configure authorization (token): token auth requires at least one token signing root certificate

goroutine 1 [running]:
panic(0xb4cd40, 0xc4203f8170)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/docker/distribution/registry/handlers.NewApp(0x1067820, 0xc4203d6090, 0xc42012dc00, 0x1067820)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:302 +0x1b6a
github.com/docker/distribution/registry.NewRegistry(0x7f15f0fa7368, 0xc4203d6090, 0xc42012dc00, 0xe, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/registry.go:86 +0x213
github.com/docker/distribution/registry.glob..func1(0x108f1a0, 0xc420347bf0, 0x1, 0x1)
	/go/src/github.com/docker/distribution/registry/registry.go:55 +0x106
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x108f1a0, 0xc420347ba0, 0x1, 0x1, 0x108f1a0, 0xc420347ba0)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x190
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x108f340, 0xc4201e5f40, 0xc4200001a0)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x3c3
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:24 +0x2d

Can someone help solve this problem ?
thanks ~

**Comment by reasonerjt** [comment]
We'll update the k8s deployment doc soon and this issue will be resolved by then.

**Comment by reasonerjt** [comment]
The document has been updated, please retry.

**Comment by lixwlixw** [comment]
#default config run harbor on kubernetes
#https://github.com/vmware/harbor/tree/master/make/kubernetes

[root@localhost ~]# docker push test.test.com/library/mysql:latest
The push refers to a repository [test.test.com/library/mysql]
e34e8fab31c1: Retrying in 1 second 
f777f53d69bd: Retrying in 1 second 
fe8901462da7: Retrying in 1 second 
b87555e2aaa4: Retrying in 1 second 
23dda9cead7e: Retrying in 1 second 
c8f3a7f8de85: Waiting 
ac3651303397: Waiting 
b5e92f2c8c83: Waiting 
a11dbc70bc19: Waiting 
f2d4d7ad289e: Waiting 
18f9b4e2e1bc: Waiting 
Error: Status 503 trying to push repository library/mysql: "<html>\n  <head>\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\n  <style type=\"text/css\">\n  /*!\n   * Bootstrap v3.3.5 (http://getbootstrap.com)\n   * Copyright 2011-2015 Twitter, Inc.\n   * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)\n   */\n  /*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */\n  html {\n    font-family: sans-serif;\n    -ms-text-size-adjust: 100%;\n    -webkit-text-size-adjust: 100%;\n  }\n  body {\n    margin: 0;\n  }\n  h1 {\n    font-size: 1.7em;\n    font-weight: 400;\n    line-height: 1.3;\n    margin: 0.68em 0;\n  }\n  * {\n    -webkit-box-sizing: border-box;\n    -moz-box-sizing: border-box;\n    box-sizing: border-box;\n  }\n  *:before,\n  *:after {\n    -webkit-box-sizing: border-box;\n    -moz-box-sizing: border-box;\n    box-sizing: border-box;\n  }\n  html {\n    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);\n  }\n  body {\n    font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n    line-height: 1.66666667;\n    font-size: 13px;\n    color: #333333;\n    background-color: #ffffff;\n    margin: 2em 1em;\n  }\n  p {\n    margin: 0 0 10px;\n    font-size: 13px;\n  }\n  .alert.alert-info {\n    padding: 15px;\n    margin-bottom: 20px;\n    border: 1px solid transparent;\n    background-color: #f5f5f5;\n    border-color: #8b8d8f;\n    color: #363636;\n    margin-top: 30px;\n  }\n  .alert p {\n    padding-left: 35px;\n  }\n  a {\n    color: #0088ce;\n  }\n\n  ul {\n    position: relative;\n    padding-left: 51px;\n  }\n  p.info {\n    position: relative;\n    font-size: 15px;\n    margin-bottom: 10px;\n  }\n  p.info:before, p.info:after {\n    content: \"\";\n    position: absolute;\n    top: 9%;\n    left: 0;\n  }\n  p.info:before {\n    content: \"i\";\n    left: 3px;\n    width: 20px;\n    height: 20px;\n    font-family: serif;\n    font-size: 15px;\n    font-weight: bold;\n    line-height: 21px;\n    text-align: center;\n    color: #fff;\n    background: #4d5258;\n    border-radius: 16px;\n  }\n\n  @media (min-width: 768px) {\n    body {\n      margin: 4em 3em;\n    }\n    h1 {\n      font-size: 2.15em;}\n  }\n\n  </style>\n  </head>\n  <body>\n    <div>\n      <h1>Application is not available</h1>\n      <p>The application is currently not serving requests at this endpoint. It may not have been started or is still starting.</p>\n\n      <div class=\"alert alert-info\">\n        <p class=\"info\">\n          Possible reasons you are seeing this page:\n        </p>\n        <ul>\n          <li>\n            <strong>The host doesn't exist.</strong>\n            Make sure the hostname was typed correctly and that a route matching this hostname exists.\n          </li>\n          <li>\n            <strong>The host exists, but doesn't have a matching path.</strong>\n            Check if the URL path was typed correctly and that the route was created using the desired path.\n          </li>\n          <li>\n            <strong>Route and path matches, but all pods are down.</strong>\n            Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.\n          </li>\n        </ul>\n      </div>\n    </div>\n  </body>\n</html>\n"

**Comment by reasonerjt** [comment]
Are you sure you are using the latest doc?  seems this is based on a very old version of Harbor.

**Comment by lixwlixw** [comment]
registry image is docker.io/vmware/registry:2.6.2-photon

**Comment by reasonerjt** [comment]
@lixwlixw and what about the other images?

**Comment by reasonerjt** [comment]
closing due to inactivity.
