### ISSUE TITLE
Harbor latest is broken in OVA builds

### ISSUE THREAD

**Issue by andrewtchin** [vmware/harbor#3351]
OVA built with latest Harbor from `harbor_builds` bucket fails with the following logs:
```
root@localhost [ ~ ]# journalctl -u harbor
Oct 02 15:47:51 localhost.localdomain start_harbor.sh[1171]: notary-server    | WARNING: no logs are available with the 'syslog' log driver
Oct 02 15:47:52 localhost.localdomain start_harbor.sh[1171]: clair exited with code 1
Oct 02 15:47:53 localhost.localdomain start_harbor.sh[1171]: clair            | WARNING: no logs are available with the 'syslog' log driver
Oct 02 15:47:53 localhost.localdomain start_harbor.sh[1171]: clair exited with code 1
Oct 02 15:47:57 localhost.localdomain start_harbor.sh[1171]: clair            | WARNING: no logs are available with the 'syslog' log driver
Oct 02 15:48:04 localhost.localdomain start_harbor.sh[1171]: harbor-ui exited with code 2
Oct 02 15:48:05 localhost.localdomain start_harbor.sh[1171]: harbor-ui        | WARNING: no logs are available with the 'syslog' log driver
Oct 02 15:48:06 localhost.localdomain start_harbor.sh[1171]: harbor-ui exited with code 2
Oct 02 15:48:06 localhost.localdomain start_harbor.sh[1171]: harbor-ui        | WARNING: no logs are available with the 'syslog' log driver
Oct 02 15:48:07 localhost.localdomain start_harbor.sh[1171]: harbor-ui exited with code 2
Oct 02 15:48:07 localhost.localdomain start_harbor.sh[1171]: harbor-ui        | WARNING: no logs are available with the 'syslog' log driver
Oct 02 15:48:08 localhost.localdomain start_harbor.sh[1171]: harbor-ui exited with code 2
Oct 02 15:48:09 localhost.localdomain start_harbor.sh[1171]: harbor-ui        | WARNING: no logs are available with the 'syslog' log driver
Oct 02 15:48:09 localhost.localdomain start_harbor.sh[1171]: harbor-ui exited with code 2
Oct 02 15:48:11 localhost.localdomain start_harbor.sh[1171]: harbor-ui        | WARNING: no logs are available with the 'syslog' log driver
Oct 02 15:48:11 localhost.localdomain start_harbor.sh[1171]: harbor-ui exited with code 2
Oct 02 15:48:15 localhost.localdomain start_harbor.sh[1171]: harbor-ui        | WARNING: no logs are available with the 'syslog' log driver
Oct 02 15:48:15 localhost.localdomain start_harbor.sh[1171]: harbor-ui exited with code 2
Oct 02 15:48:22 localhost.localdomain start_harbor.sh[1171]: harbor-ui        | WARNING: no logs are available with the 'syslog' log driver
Oct 02 15:48:22 localhost.localdomain start_harbor.sh[1171]: harbor-ui exited with code 2
Oct 02 15:48:35 localhost.localdomain start_harbor.sh[1171]: harbor-ui        | WARNING: no logs are available with the 'syslog' log driver
Oct 02 15:48:35 localhost.localdomain start_harbor.sh[1171]: harbor-ui exited with code 2
Oct 02 15:49:01 localhost.localdomain start_harbor.sh[1171]: harbor-ui        | WARNING: no logs are available with the 'syslog' log driver
Oct 02 15:49:02 localhost.localdomain start_harbor.sh[1171]: harbor-ui exited with code 2
Oct 02 15:49:53 localhost.localdomain start_harbor.sh[1171]: harbor-ui        | WARNING: no logs are available with the 'syslog' log driver
Oct 02 15:49:53 localhost.localdomain start_harbor.sh[1171]: harbor-ui exited with code 2
Oct 02 15:50:54 localhost.localdomain start_harbor.sh[1171]: harbor-ui        | WARNING: no logs are available with the 'syslog' log driver
Oct 02 15:50:54 localhost.localdomain start_harbor.sh[1171]: harbor-ui exited with code 2
Oct 02 15:51:54 localhost.localdomain start_harbor.sh[1171]: harbor-ui        | WARNING: no logs are available with the 'syslog' log driver
Oct 02 15:51:55 localhost.localdomain start_harbor.sh[1171]: harbor-ui exited with code 2
```

Example appliance at root:password@10.192.208.118

**Comment by reasonerjt** [comment]
ui.log has following messages:
```
Oct  3 14:51:12 172.18.0.1 ui[391]: panic: runtime error: invalid memory address or nil pointer dereference
Oct  3 14:51:12 172.18.0.1 ui[391]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x531542]
Oct  3 14:51:12 172.18.0.1 ui[391]:
Oct  3 14:51:12 172.18.0.1 ui[391]: goroutine 1 [running]:
Oct  3 14:51:12 172.18.0.1 ui[391]: panic(0xb37fe0, 0xc42000c060)
Oct  3 14:51:12 172.18.0.1 ui[391]: #011/usr/local/go/src/runtime/panic.go:500 +0x1a1
Oct  3 14:51:12 172.18.0.1 ui[391]: github.com/vmware/harbor/src/ui/api.projectExists(0x0, 0x0, 0xc420248ba0, 0x1a, 0x0, 0x0, 0x0)
Oct  3 14:51:12 172.18.0.1 ui[391]: #011/go/src/github.com/vmware/harbor/src/ui/api/utils.go:364 +0x52
Oct  3 14:51:12 172.18.0.1 ui[391]: github.com/vmware/harbor/src/ui/api.diffRepos(0xc420344e90, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0xbfa779, 0x10, ...)
Oct  3 14:51:12 172.18.0.1 ui[391]: #011/go/src/github.com/vmware/harbor/src/ui/api/utils.go:325 +0xac8
Oct  3 14:51:12 172.18.0.1 ui[391]: github.com/vmware/harbor/src/ui/api.SyncRegistry(0x0, 0x0, 0x1, 0xc65050)
Oct  3 14:51:12 172.18.0.1 ui[391]: #011/go/src/github.com/vmware/harbor/src/ui/api/utils.go:193 +0x2b0
Oct  3 14:51:12 172.18.0.1 ui[391]: main.main()
Oct  3 14:51:12 172.18.0.1 ui[391]: #011/go/src/github.com/vmware/harbor/src/ui/main.go:136 +0x3c1
```

Checked the code the projectmanager when integrated with Admiral is Nil now.

**Comment by wy65701436** [comment]
Could we think about to add one more case to test this integrated env?

**Comment by ywk253100** [comment]
The master code cannot work well when integrated with Admiral as we are doing some refactoring to apply project level policy to standalone Harbor #3160.

**Comment by mdubya66** [comment]
we need to work on keeping master working. Making this high priority. @mhagen-vmware @mlh78750

**Comment by ywk253100** [comment]
@andrewtchin The issue will be fixed before the end of Friday.

**Comment by ywk253100** [comment]
The changes have been merged into branch master.
