### ISSUE TITLE
harbor-ui - throws runtime exception after initializing

### ISSUE THREAD

**Issue by Skewled** [vmware/harbor#3357]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.

[root@ip-172-16-0-227 ui]# docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   7392c3b/17.03.2-ce
 Built:        Wed Aug  9 22:45:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   7392c3b/17.03.2-ce
 Built:        Wed Aug  9 22:45:09 2017
 OS/Arch:      linux/amd64
 Experimental: false

[root@ip-172-16-0-227 ui]# docker logs -f 58d7ca57fa4d
2017-10-09T20:24:42Z [INFO] Config path: /etc/ui/app.conf
2017-10-09T20:24:42Z [INFO] initializing configurations...
2017-10-09T20:24:42Z [INFO] key path: /etc/ui/key
2017-10-09T20:24:42Z [INFO] initializing client for adminserver http://adminserver ...
2017-10-09T20:24:42Z [INFO] initializing the project manager based on database...
**2017-10-09T20:24:42Z [INFO] configurations initialization completed
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0xb3ad40, 0xc42000c0b0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/vmware/harbor/src/ui/config.ExtURL(0xb36640, 0xc420273ef0, 0xc420237ce8, 0xc420237cd8)
	/go/src/github.com/vmware/harbor/src/ui/config/config.go:215 +0xb7
github.com/vmware/harbor/src/ui/service/token.InitCreators()
	/go/src/github.com/vmware/harbor/src/ui/service/token/creator.go:52 +0x215
main.main()
	/go/src/github.com/vmware/harbor/src/ui/main.go:86 +0x22e**

Using default harbor.cfg file.

Would like to know what possible issues can cause this within the UI?

**Comment by ywk253100** [comment]
Did you configure "hostname" and "ui_url_protocol" in harbor.cfg correctly? Could you provide your harbor.cfg?

**Comment by Skewled** [comment]
harbor.cfg

`## Configuration file of Harbor

#The IP address or hostname to access admin UI and registry service.
#DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname = ui

#The protocol for accessing the UI and token/notification service, by default it is http.
#It can be set to https if ssl is enabled on nginx.
ui_url_protocol = http

#The password for the root user of mysql db, change this before any production use.
db_password = root123

#Maximum number of job workers in job service  
max_job_workers = 3 

#Determine whether or not to generate certificate for the registry's token.
#If the value is on, the prepare script creates new root cert and private key 
#for generating token to access the registry. If the value is off the default key/cert will be used.
#This flag also controls the creation of the notary signer's cert.
customize_crt = on

#The path of cert and key files for nginx, they are applied only the protocol is set to https
ssl_cert = /data/cert/server.crt
ssl_cert_key = /data/cert/server.key

#The path of secretkey storage
secretkey_path = /data

#Admiral's url, comment this attribute, or set its value to NA when Harbor is standalone
admiral_url = NA

#The password of the Clair's postgres database, only effective when Harbor is deployed with Clair.
#Please update it before deployment, subsequent update will cause Clair's API server and Harbor unable to access Clair's database.
clair_db_password = password

#NOTES: The properties between BEGIN INITIAL PROPERTIES and END INITIAL PROPERTIES
#only take effect in the first boot, the subsequent changes of these properties 
#should be performed on web ui

#************************BEGIN INITIAL PROPERTIES************************

#Email account settings for sending out password resetting emails.

#Email server uses the given username and password to authenticate on TLS connections to host and act as identity.
#Identity left blank to act as username.
email_identity = 

email_server = smtp.mydomain.com
email_server_port = 25
email_username = sample_admin@mydomain.com
email_password = abc
email_from = admin <sample_admin@mydomain.com>
email_ssl = false

##The initial password of Harbor admin, only works for the first time when Harbor starts. 
#It has no effect after the first launch of Harbor.
#Change the admin password from UI after launching Harbor.
harbor_admin_password = Harbor12345

##By default the auth mode is db_auth, i.e. the credentials are stored in a local database.
#Set it to ldap_auth if you want to verify a user's credentials against an LDAP server.
auth_mode = db_auth

#The url for an ldap endpoint.
ldap_url = ldaps://ldap.mydomain.com

#A user's DN who has the permission to search the LDAP/AD server. 
#If your LDAP/AD server does not support anonymous search, you should configure this DN and ldap_search_pwd.
#ldap_searchdn = uid=searchuser,ou=people,dc=mydomain,dc=com

#the password of the ldap_searchdn
#ldap_search_pwd = password

#The base DN from which to look up a user in LDAP/AD
ldap_basedn = ou=people,dc=mydomain,dc=com

#Search filter for LDAP/AD, make sure the syntax of the filter is correct.
#ldap_filter = (objectClass=person)

# The attribute used in a search to match a user, it could be uid, cn, email, sAMAccountName or other attributes depending on your LDAP/AD  
ldap_uid = uid 

#the scope to search for users, 1-LDAP_SCOPE_BASE, 2-LDAP_SCOPE_ONELEVEL, 3-LDAP_SCOPE_SUBTREE
ldap_scope = 3 

#Timeout (in seconds)  when connecting to an LDAP Server. The default value (and most reasonable) is 5 seconds.
ldap_timeout = 5

#Turn on or off the self-registration feature
self_registration = on

#The expiration time (in minute) of token created by token service, default is 30 minutes
token_expiration = 30

#The flag to control what users have permission to create projects
#The default value "everyone" allows everyone to creates a project. 
#Set to "adminonly" so that only admin user can create project.
project_creation_restriction = everyone

#Determine whether the job service should verify the ssl cert when it connects to a remote registry.
#Set this flag to off when the remote registry uses a self-signed or untrusted certificate.
verify_remote_cert = on
#************************END INITIAL PROPERTIES************************
#############
`
I'll check the hostname but it is named ui and linked to the other containers.

**Comment by Skewled** [comment]
Updated hostname to the IP of the box running all the docker containers.

**Comment by ywk253100** [comment]
Provide your config.json under directory /data/config/.

**Comment by Skewled** [comment]
`{
  "admin_initial_password": "\u003cenc-v1\u003eVYPpODVgzRgvkNWL3PsdWLgnQ+FDH33AUsrp",
  "admiral_url": "NA",
  "auth_mode": "db_auth",
  "cfg_expiration": 5,
  "clair_db_password": "\u003cenc-v1\u003eyTbKQhxebkn6fZ8ZLLZgHLCTJWKVD4WS",
  "database_type": "mysql",
  "email_from": "",
  "email_host": "",
  "email_identity": "",
  "email_password": "\u003cenc-v1\u003ed17JvGJykwgvmfzSA4zr5w==",
  "email_port": 0,
  "email_ssl": false,
  "email_username": "",
  "ext_endpoint": "",
  "ldap_base_dn": "",
  "ldap_filter": "",
  "ldap_scope": 0,
  "ldap_search_dn": "",
  "ldap_search_password": "\u003cenc-v1\u003ebHXYp/EIvp4BP5aSWSg8HA==",
  "ldap_timeout": 0,
  "ldap_uid": "",
  "ldap_url": "",
  "max_job_workers": 3,
  "mysql_database": "registry",
  "mysql_host": "mysql",
  "mysql_password": "\u003cenc-v1\u003eeMMUPmUycMj75XvA+I+FyWBmzxE8m1M=",
  "mysql_port": 3306,
  "mysql_username": "root",
  "project_creation_restriction": "everyone",
  "registry_url": "http://registry:5000",
  "self_registration": true,
  "sqlite_file": "",
  "token_expiration": 30,
  "verify_remote_cert": true,
  "with_clair": false,
  "with_notary": false
}
`

**Comment by ywk253100** [comment]
The root cause is that the property `ext_endpoint ` in config.json is null. 
Run the following commands:
```
docker-compose down
./prepare
docker-compose up -d
```
These will reload configurations from harbor.cfg.

Please check whether the property has a valid value after you running the commands.

**Comment by Skewled** [comment]
@ywk253100 
When I run the prepare script I receive the below error:
`Fail to generate key file: ./common/config/ui/private_key.pem, cert file: ./common/config/registry/root.crt`

The `root.crt` file is not present on my system.

Please advise, thank you.

**Comment by ywk253100** [comment]
Is there any other output to explain why it failed?

**Comment by Skewled** [comment]
There is no other output given, the only error received during the prepare phase is that root.crt file is not present on the system. I observed private_key.pem is 0kb in size, there are no other items which throw out errors.

**Comment by ywk253100** [comment]
We can not reproduce the issue, can you try to debug why the error occurred in your environment?

**Comment by Skewled** [comment]
Good Morning,

I've gone over each container relevant to this, here is the docker log output. I cannot seem to find any particular item throwing any issues except for the out of range index error. If there are any additional debug steps I can take to help towards resolution, please let me know.

**Environment:** AWS ECS
Containers launch but exit after the habor-ui container fails.
No logging is enabled.

**harbor-ui**
```
docker logs -f 7287b746e62c
2017-10-31T13:24:22Z [INFO] Config path: /etc/ui/app.conf
2017-10-31T13:24:22Z [INFO] initializing configurations...
2017-10-31T13:24:22Z [INFO] key path: /etc/ui/key
2017-10-31T13:24:22Z [INFO] initializing client for adminserver http://adminserver ...
2017-10-31T13:24:22Z [INFO] initializing the project manager based on database...
2017-10-31T13:24:22Z [INFO] configurations initialization completed
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0xb3ad40, 0xc42000c0b0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/vmware/harbor/src/ui/config.ExtURL(0xb36640, 0xc420372780, 0xc420235ce8, 0xc420235cd8)
	/go/src/github.com/vmware/harbor/src/ui/config/config.go:215 +0xb7
github.com/vmware/harbor/src/ui/service/token.InitCreators()
	/go/src/github.com/vmware/harbor/src/ui/service/token/creator.go:52 +0x215
main.main()
	/go/src/github.com/vmware/harbor/src/ui/main.go:86 +0x22e
```

**harbor-adminserver**
```
docker logs -f 00fa68675278
2017-10-31T13:24:21Z [INFO] initializing system configurations...
2017-10-31T13:24:21Z [INFO] the path of json configuration storage: /etc/adminserver/config/config.json
2017-10-31T13:24:21Z [DEBUG] [driver_json.go:46]: path of configuration file: /etc/adminserver/config/config.json
2017-10-31T13:24:21Z [INFO] the path of key used by key provider: /etc/adminserver/key
2017-10-31T13:24:21Z [INFO] system initialization completed
172.17.0.6 - - [31/Oct/2017:13:24:22 +0000] "GET /api/configurations HTTP/1.1" 200 786
```

**harbor-db**
```
docker logs 924d5cf426af
2017-10-31 13:24:21 0 [Note] mysqld (mysqld 5.6.35) starting as process 1 ...
2017-10-31 13:24:21 1 [Warning] Buffered warning: Changed limits: max_open_files: 1024 (requested 5000)

2017-10-31 13:24:21 1 [Warning] Buffered warning: Changed limits: table_open_cache: 431 (requested 2000)

2017-10-31 13:24:21 1 [Note] Plugin 'FEDERATED' is disabled.
2017-10-31 13:24:21 1 [Note] InnoDB: Using atomics to ref count buffer pool pages
2017-10-31 13:24:21 1 [Note] InnoDB: The InnoDB memory heap is disabled
2017-10-31 13:24:21 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2017-10-31 13:24:21 1 [Note] InnoDB: Memory barrier is not used
2017-10-31 13:24:21 1 [Note] InnoDB: Compressed tables use zlib 1.2.8
2017-10-31 13:24:21 1 [Note] InnoDB: Using Linux native AIO
2017-10-31 13:24:21 1 [Note] InnoDB: Using CPU crc32 instructions
2017-10-31 13:24:21 1 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2017-10-31 13:24:21 1 [Note] InnoDB: Completed initialization of buffer pool
2017-10-31 13:24:21 1 [Note] InnoDB: Highest supported file format is Barracuda.
2017-10-31 13:24:21 1 [Note] InnoDB: 128 rollback segment(s) are active.
2017-10-31 13:24:21 1 [Note] InnoDB: Waiting for purge to start
2017-10-31 13:24:21 1 [Note] InnoDB: 5.6.35 started; log sequence number 1936846
2017-10-31 13:24:21 1 [Note] Server hostname (bind-address): '*'; port: 3306
2017-10-31 13:24:21 1 [Note] IPv6 is available.
2017-10-31 13:24:21 1 [Note]   - '::' resolves to '::';
2017-10-31 13:24:21 1 [Note] Server socket created on IP: '::'.
2017-10-31 13:24:21 1 [Warning] 'proxies_priv' entry '@ root@ip-172-16-0-227' ignored in --skip-name-resolve mode.
2017-10-31 13:24:21 1 [Note] Event Scheduler: Loaded 0 events
2017-10-31 13:24:21 1 [Note] mysqld: ready for connections.
Version: '5.6.35'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
2017-10-31 13:24:22 1 [Note] mysqld: Normal shutdown

2017-10-31 13:24:22 1 [Note] Giving 0 client threads a chance to die gracefully
2017-10-31 13:24:22 1 [Note] Event Scheduler: Purging the queue. 0 events
2017-10-31 13:24:22 1 [Note] Shutting down slave threads
2017-10-31 13:24:22 1 [Note] Forcefully disconnecting 0 remaining clients
2017-10-31 13:24:22 1 [Note] Binlog end
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'partition'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_FT_DELETED'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_METRICS'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_CMPMEM'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_CMP_RESET'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_CMP'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_LOCKS'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'INNODB_TRX'
2017-10-31 13:24:22 1 [Note] Shutting down plugin 'InnoDB'
2017-10-31 13:24:22 1 [Note] InnoDB: FTS optimize thread exiting.
2017-10-31 13:24:22 1 [Note] InnoDB: Starting shutdown...
2017-10-31 13:24:24 1 [Note] InnoDB: Shutdown completed; log sequence number 1936856
2017-10-31 13:24:24 1 [Note] Shutting down plugin 'BLACKHOLE'
2017-10-31 13:24:24 1 [Note] Shutting down plugin 'ARCHIVE'
2017-10-31 13:24:24 1 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
2017-10-31 13:24:24 1 [Note] Shutting down plugin 'MRG_MYISAM'
2017-10-31 13:24:24 1 [Note] Shutting down plugin 'MyISAM'
2017-10-31 13:24:24 1 [Note] Shutting down plugin 'CSV'
2017-10-31 13:24:24 1 [Note] Shutting down plugin 'MEMORY'
2017-10-31 13:24:24 1 [Note] Shutting down plugin 'sha256_password'
2017-10-31 13:24:24 1 [Note] Shutting down plugin 'mysql_old_password'
2017-10-31 13:24:24 1 [Note] Shutting down plugin 'mysql_native_password'
2017-10-31 13:24:24 1 [Note] Shutting down plugin 'binlog'
2017-10-31 13:24:24 1 [Note] mysqld: Shutdown complete
```

**registry**
```
> docker logs 79a980b2b240
> time="2017-10-31T13:24:21Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.7.3 instance.id=059576c3-29e1-4eed-bc3d-e3bdae2a9f94 version=v2.6.2 
> time="2017-10-31T13:24:21Z" level=info msg="redis not configured" go.version=go1.7.3 instance.id=059576c3-29e1-4eed-bc3d-e3bdae2a9f94 version=v2.6.2 
> time="2017-10-31T13:24:21Z" level=info msg="Starting upload purge in 26m0s" go.version=go1.7.3 instance.id=059576c3-29e1-4eed-bc3d-e3bdae2a9f94 version=v2.6.2 
> time="2017-10-31T13:24:21Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.7.3 instance.id=059576c3-29e1-4eed-bc3d-e3bdae2a9f94 version=v2.6.2 
> time="2017-10-31T13:24:21Z" level=info msg="listening on [::]:5000" go.version=go1.7.3 instance.id=059576c3-29e1-4eed-bc3d-e3bdae2a9f94 version=v2.6.2
```

**postgresql**
```
docker logs 50862c5f2c7a
here1
LOG:  database system was shut down at 2017-10-31 13:24:09 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  autovacuum launcher started
LOG:  database system is ready to accept connections

Session terminated, terminating shell...LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
 ...terminated.
```

**Comment by ywk253100** [comment]
The root cause of the error `panic: runtime error: index out of range` is that the property `ext_endpoint` is null in `/data/config/config.json` as I mentioned above.

Run `prepare` should fix this, but another error occurred when you ran this command, so I mean you can debug why there was an error when you ran `prepare`.

Or you can just edit the `/data/config/config.json` to set the property `ext_endpoint` with `ui_url_protocol://hostname`. Replace the `ui_url_protocol ` and `hostname` with the values in harbor.cfg.

**Comment by Skewled** [comment]
I modified those values earlier in our discussion, immediately after you brought them to my attention.

After inspecting the system it appears the ```/data/config/config.json``` file is overwritten by something, the values in ```harbor.cfg``` are set properly, and the ```prepare.sh``` script runs perfectly fine now.

So, what is causing this file ```/data/config/config.json``` to be overwritten and where do I modify it to ensure my changes stick so the containers stay online?

**Comment by ywk253100** [comment]
The script `prepare` populates the configuration items into `env` files under directory `common/config/component_name/`, and the key/value pairs in the `env` files are set as environment variables inside containers, the programs load the variables for some initialization work.

The `ext_endpoint` is one config of `adminserver`, but I don't see it in your JSON file https://github.com/Skewled/harbor/blob/master/harbor.json#L122.

**Comment by Skewled** [comment]
That brought the containers online and produced a 502 gateway error, but at least the index error is resolved.

```2017/11/02 13:35:01 [error] 6#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.3.5.123, server: , request: "GET / HTTP/1.1", upstream: "http://172.17.0.6:80/", host: "172.16.0.201"
10.3.5.123 - "GET / HTTP/1.1" 502 576 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" 0.000 0.000 .
2017/11/02 13:35:01 [error] 6#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.3.5.123, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.17.0.6:80/favicon.ico", host: "172.16.0.201", referrer: "http://172.16.0.201/"
10.3.5.123 - "GET /favicon.ico HTTP/1.1" 502 576 "http://172.16.0.201/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" 0.000 0.000 ```

I believe these errors are from missing variables in the config file, would you please tell me which variables are associated to which container so I can assign them appropriately?

I'm very thankful for your help and patience, seeing that 502 and the containers come online made my day.

**Comment by ywk253100** [comment]
You can refer to `env` files for each component under directory `common/config/component_name/`.

**Comment by Skewled** [comment]
Thanks for the assistance! :)
