### ISSUE TITLE
./install.sh   harbor error

### ISSUE THREAD

**Issue by depfish** [vmware/harbor#3358]
root@ip-10-250-3-75:/opt/harbor/make# pwd
/opt/harbor/make
root@ip-10-250-3-75:/opt/harbor/make# ./install.sh 

[Step 0]: checking installation environment ...

Note: docker version: 17.07.0

Note: docker-compose version: 1.7.0

[Step 1]: preparing environment ...
Traceback (most recent call last):
  File "./prepare", line 110, in <module>
    validate(rcp, args)
  File "./prepare", line 37, in validate
    project_creation = rcp.get("configuration", "project_creation_restriction")
  File "/usr/lib/python2.7/ConfigParser.py", line 340, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option u'project_creation_restriction' in section: u'configuration'
root@ip-10-250-3-75:/opt/harbor/make#

**Comment by depfish** [comment]
config issue
