### ISSUE TITLE
Replicate Image Failed

### ISSUE THREAD

**Issue by steveal** [vmware/harbor#3609]
Sorry.My English is very poor. 

Replicate Image Failed
docker Server Version: 17.03.0-ce  
docker-compose version : 1.10.0-rc2, build fb241d0  
Harbor version: v1.1.2

The Replicate ability is amazing, but when I trying to some kind of image, it failed.  
I found the structure of image addrees could affect the replicate function. Just My guss :).  
Below is my test:  
1. I have two machine, MachineA(10.45.80.21), MachineB(10.45.80.22),both I intall harbor v1.1.2 and Create Project "ztp"  
I cofigure replicate rule in MachineB to replicate image to MachineB.
2. I push image to MachineB, ```docker push 10.45.80.22/ztp/test/busybox```  
then there is a replicate job on page. But The image can't replicate to MachineA.  The vmware/harbor-jobservice container on MachineB status is Restarting

MachineB : jobservice.log 
```
Nov 14 11:22:38 172.18.0.1 jobservice[1271]: 2017-11-14T03:22:38Z [DEBUG] [transport.go:50]: 200 | GET http://registry:5000/v2/ztp/test/busybox/tags/list
Nov 14 11:22:38 172.18.0.1 jobservice[1271]: 2017-11-14T03:22:38Z [DEBUG] [statemachine.go:88]: Job id: 3397, transition succeeded, current state: initialize
Nov 14 11:22:38 172.18.0.1 jobservice[1271]: 2017-11-14T03:22:38Z [DEBUG] [statemachine.go:118]: Job id: 3397, next state from handler: check
Nov 14 11:22:38 172.18.0.1 jobservice[1271]: 2017-11-14T03:22:38Z [DEBUG] [statemachine.go:61]: Job id: 3397, transiting from State: initialize, to State: check
Nov 14 11:22:38 172.18.0.1 jobservice[1271]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 14 11:22:38 172.18.0.1 jobservice[1271]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x72955d]
Nov 14 11:22:38 172.18.0.1 jobservice[1271]: 
Nov 14 11:22:38 172.18.0.1 jobservice[1271]: goroutine 36 [running]:
Nov 14 11:22:38 172.18.0.1 jobservice[1271]: panic(0x9c6d60, 0xc42000c060)
Nov 14 11:22:38 172.18.0.1 jobservice[1271]: #011/usr/local/go/src/runtime/panic.go:500 +0x1a1
Nov 14 11:22:38 172.18.0.1 jobservice[1271]: github.com/vmware/harbor/src/jobservice/replication.(*Checker).enter(0xc42033a0c8, 0xf2bca0, 0x414f50, 0xc420041a50, 0x6accd486)
Nov 14 11:22:38 172.18.0.1 jobservice[1271]: #011/go/src/github.com/vmware/harbor/src/jobservice/replication/transfer.go:195 +0x19d
```
replicate job log:
```
2017-11-14T03:22:36Z [INFO] initializing: repository: ztp/test/busybox, tags: [], source URL: http://registry:5000, destination URL: http://10.45.80.21, insecure: false, destination user: admin
2017-11-14T03:22:36Z [INFO] initialization completed: project: ztp/test, repository: ztp/test/busybox, tags: [latest], source URL: http://registry:5000, destination URL: http://10.45.80.21, insecure: false, destination user: admin
2017-11-14T03:22:37Z [INFO] initializing: repository: ztp/test/busybox, tags: [], source URL: http://registry:5000, destination URL: http://10.45.80.21, insecure: false, destination user: admin
2017-11-14T03:22:37Z [INFO] initialization completed: project: ztp/test, repository: ztp/test/busybox, tags: [latest], source URL: http://registry:5000, destination URL: http://10.45.80.21, insecure: false, destination user: admin
2017-11-14T03:22:38Z [INFO] initializing: repository: ztp/test/busybox, tags: [], source URL: http://registry:5000, destination URL: http://10.45.80.21, insecure: false, destination user: admin
2017-11-14T03:22:38Z [INFO] initialization completed: project: ztp/test, repository: ztp/test/busybox, tags: [latest], source URL: http://registry:5000, destination URL: http://10.45.80.21, insecure: false, destination user: admin
2017-11-14T03:22:38Z [INFO] initializing: repository: ztp/test/busybox, tags: [], source URL: http://registry:5000, destination URL: http://10.45.80.21, insecure: false, destination user: admin
2017-11-14T03:22:39Z [INFO] initialization completed: project: ztp/test, repository: ztp/test/busybox, tags: [latest], source URL: http://registry:5000, destination URL: http://10.45.80.21, insecure: false, destination user: admin
2017-11-14T03:22:40Z [INFO] initializing: repository: ztp/test/busybox, tags: [], source URL: http://registry:5000, destination URL: http://10.45.80.21, insecure: false, destination user: admin
```
3.  I disable replicate rule ,and delete ```10.45.80.22/ztp/test/busybox``` on Harbor, The vmware/harbor-jobservice container on MachineB status chang to UP
4.  I push image ```docker push 10.45.80.22/ztp/busybox```, the replicate functin work fine

In my guess, replicate  function don't support image address like ```10.45.80.22/ztp/test/busybox```, the image address must be like HarborAddress/Project/ImageName:Tag, not like HarborAddress/Project1/Project2/ImageName:Tag or more layers.

**Comment by ywk253100** [comment]
It's a known issue and has been fixed in 1.2. Please upgrade to the latest version.
