### ISSUE TITLE
nil pointer deref when CONFIG_PATH env var is wrong

### ISSUE THREAD

**Issue by SEJeff** [vmware/harbor#40]
```bash
jschroeder@chit-jsl2:/tmp/harbor/config/ui (master *)$ harbor
2016/03/24 12:01:56 Config path: /etc/ui/harbor.conf
2016-03-24T12:01:56-05:00 [INFO] User id: 1 already has its encrypted password.
^Cjschroeder@chit-jsl2:/tmp/harbor/config/ui (master *)$ export CONFIG_PATH=/bogus/path
jschroeder@chit-jsl2:/tmp/harbor/config/ui (master *)$ harbor
2016/03/24 12:02:16 Config path: /bogus/path
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5302c2]

goroutine 1 [running]:
github.com/vmware/harbor/vendor/github.com/astaxie/beego.(*beegoAppConfig).String(0x0, 0xbccbf0, 0xb, 0x0, 0x0)
	/builddir/build/BUILD/harbor-a61cf3625a162811a5d467cff8291438a0025914/_build/src/github.com/vmware/harbor/vendor/github.com/astaxie/beego/config.go:299 +0x172
github.com/vmware/harbor/controllers.init.1()
	/builddir/build/BUILD/harbor-a61cf3625a162811a5d467cff8291438a0025914/_build/src/github.com/vmware/harbor/controllers/base.go:136 +0x515
github.com/vmware/harbor/controllers.init()
	/builddir/build/BUILD/harbor-a61cf3625a162811a5d467cff8291438a0025914/_build/src/github.com/vmware/harbor/controllers/search.go:28 +0x81
github.com/vmware/harbor/routers.init()
	/builddir/build/BUILD/harbor-a61cf3625a162811a5d467cff8291438a0025914/_build/src/github.com/vmware/harbor/routers/router.go:66 +0x40
main.init()
	/builddir/build/BUILD/harbor-a61cf3625a162811a5d467cff8291438a0025914/main.go:75 +0x59

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [runnable]:
time.NewTimer(0xa7a3582000, 0x0)
	/usr/local/go/src/time/sleep.go:67 +0x30
time.After(0xa7a3582000, 0x0)
	/usr/local/go/src/time/sleep.go:110 +0x21
github.com/vmware/harbor/vendor/github.com/astaxie/beego/cache.(*MemoryCache).vaccuum(0xc820112c60)
	/builddir/build/BUILD/harbor-a61cf3625a162811a5d467cff8291438a0025914/_build/src/github.com/vmware/harbor/vendor/github.com/astaxie/beego/cache/memory.go:216 +0x4e
created by github.com/vmware/harbor/vendor/github.com/astaxie/beego/cache.(*MemoryCache).StartAndGC
	/builddir/build/BUILD/harbor-a61cf3625a162811a5d467cff8291438a0025914/_build/src/github.com/vmware/harbor/vendor/github.com/astaxie/beego/cache/memory.go:206 +0x270
```

I plan on fixing this perhaps this weekend and making it give a bit nicer message. Just wanted to file this so it does eventually get fixed. The weird paths are due to me building harbor via a rpm spec file with mock.

Would you be interested in a spec file for an rpm?

**Comment by reasonerjt** [comment]
@SEJeff 
May I know what is the "bogus/path"?
We call the method in beego to parse the config, I checked the code it should not parse it as a nil without any error.  

And yes the spec file would be helpful for us to investigate other approach for installation, though we may not immediately merge it into the repo, could you attach the spec file in this issue?

**Comment by hainingzhang** [comment]
closing this for no response. Please reopen if needed.
