### ISSUE TITLE
make offline package failing with missing clarity-seed json

### ISSUE THREAD

**Issue by tomsherrod** [vmware/harbor#4019]
What am I missing?

docker version: 17.12.0
docker-compose version: 1.8.0

make package_offline GOBUILDIMAGE=golang:1.7.3 COMPILETAG=compile_golangimage CLARITYIMAGE=vmware/harbor-clarity-ui-b[16/1198$
8.4 CLAIRFLAG=true NOTARYFLAG=true HTTPPROXY=

compiling binary for clarity ui...
npm info it worked if it ends with ok
npm info using npm@4.1.2
npm info using node@v7.5.0
npm info attempt registry request try #1 at 1:34:21 PM
npm http request GET https://registry.npmjs.org/fsevents
npm http 200 https://registry.npmjs.org/fsevents
npm info lifecycle harbor@0.6.0~preinstall: harbor@0.6.0
npm info linkStuff harbor@0.6.0
npm info lifecycle harbor@0.6.0~install: harbor@0.6.0
npm info lifecycle harbor@0.6.0~postinstall: harbor@0.6.0
npm info lifecycle harbor@0.6.0~prepublish: harbor@0.6.0
npm info lifecycle harbor@0.6.0~prepare: harbor@0.6.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN codelyzer@1.0.0-beta.4 requires a peer of tslint@^3.9.0 but none was installed.
npm WARN codelyzer@1.0.0-beta.4 requires a peer of @angular/compiler@~2.2.0 but none was installed.
npm WARN codelyzer@1.0.0-beta.4 requires a peer of @angular/core@~2.2.0 but none was installed.
npm info ok 
ENOENT: no such file or directory, stat '/clarity-seed/src/tsconfig.json'
Error: ENOENT: no such file or directory, stat '/clarity-seed/src/tsconfig.json'
    at Object.fs.statSync (fs.js:907:18)
    at AotPlugin._setupOptions (/clarity-seed/node_modules/@ngtools/webpack/src/plugin.js:58:16)
    at new AotPlugin (/clarity-seed/node_modules/@ngtools/webpack/src/plugin.js:26:14)
    at _createAotPlugin (/clarity-seed/node_modules/@angular/cli/models/webpack-configs/typescript.js:55:12)
    at Object.exports.getNonAotConfig (/clarity-seed/node_modules/@angular/cli/models/webpack-configs/typescript.js:70:19)
    at NgCliWebpackConfig.buildConfig (/clarity-seed/node_modules/@angular/cli/models/webpack-config.js:27:37)
    at Class.run (/clarity-seed/node_modules/@angular/cli/tasks/build.js:26:92)
    at Class.run (/clarity-seed/node_modules/@angular/cli/commands/build.js:143:26)
    at Class.<anonymous> (/clarity-seed/node_modules/@angular/cli/ember-cli/lib/models/command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Makefile:252: recipe for target 'compile_clarity' failed
make: *** [compile_clarity] Error 1

**Comment by steven-zou** [comment]
@tomsherrod Which code branch are you using to build? Latest master? if yes, please try
```
sudo make install GOBUILDIMAGE=golang:1.9.2 COMPILETAG=compile_golangimage CLARITYIMAGE=vmware/harbor-clarity-ui-builder:1.3.0 NOTARYFLAG=true CLAIRFLAG=true
```

golang image and ui builder image versions are updated

**Comment by tomsherrod** [comment]
That did the trick. Thanks!
