### ISSUE TITLE
Adminserver panic when handling LDAP scope

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#4073]
```
Jan 18 18:45:32 172.18.0.1 adminserver[8733]: panic: interface conversion: interface {} is float64, n$t int
Jan 18 18:45:32 172.18.0.1 adminserver[8733]: 
Jan 18 18:45:32 172.18.0.1 adminserver[8733]: goroutine 1 [running]:
Jan 18 18:45:32 172.18.0.1 adminserver[8733]: github.com/vmware/harbor/src/adminserver/systemcfg.vali$LdapScope(...)
Jan 18 18:45:32 172.18.0.1 adminserver[8733]: #011/go/src/github.com/vmware/harbor/src/adminserver/sy$temcfg/systemcfg.go:368
Jan 18 18:45:32 172.18.0.1 adminserver[8733]: github.com/vmware/harbor/src/adminserver/systemcfg.Load$romEnv(0xc4201b5aa0, 0xc4201b5a00, 0x0, 0x0)
Jan 18 18:45:32 172.18.0.1 adminserver[8733]: #011/go/src/github.com/vmware/harbor/src/adminserver/sys
temcfg/systemcfg.go:345 +0x7a9
Jan 18 18:45:32 172.18.0.1 adminserver[8733]: github.com/vmware/harbor/src/adminserver/systemcfg.Init(
0xc4200fdf40, 0x1)
Jan 18 18:45:32 172.18.0.1 adminserver[8733]: #011/go/src/github.com/vmware/harbor/src/adminserver/sys
temcfg/systemcfg.go:228 +0xc5
Jan 18 18:45:32 172.18.0.1 adminserver[8733]: main.main()
Jan 18 18:45:32 172.18.0.1 adminserver[8733]: #011/go/src/github.com/vmware/harbor/src/adminserver/mai
n.go:45 +0x7e
```

**Comment by stonezdj** [comment]
fixed in #4074
