### ISSUE TITLE
ui_1 failed to start when deploying harbor by docker-compose up

### ISSUE THREAD

**Issue by luckyfengyong** [vmware/harbor#495]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose
Docker version 1.11.2, build b9f10c9
docker-compose version 1.6.0, build d99cad6
2)Config files of harbor, you can get them by packaging "Deploy/config" directory
default
3)Log files, you can get them by package the /var/log/harbor/ 

ui_1 failed to start with following messages. The issue could be fixed by adding "mysql" as depends_on of service of "ui" in docker-compose.yml.

ui_1       | 2016-07-07T09:24:47Z [DEBUG] [base.go:74]: db url: mysql:3306, db user: root
ui_1       | [ORM]register db Ping `default`, dial tcp 172.17.0.4:3306: getsockopt: connection refused
ui_1       | 2016-07-07T09:24:47Z [ERROR] [base.go:86]: failed to connect to db, retry after 2 seconds :dial tcp 172.17.0.4:3306: getsockopt: connection refused
ui_1       | panic: register db Ping `default`, dial tcp 172.17.0.4:3306: getsockopt: connection refused
ui_1       |
ui_1       | goroutine 1 [running]:
ui_1       | panic(0xab4c40, 0xc82000a180)
ui_1       |    /usr/local/go/src/runtime/panic.go:481 +0x3e6
ui_1       | github.com/vmware/harbor/dao.InitDB()
ui_1       |    /go/src/github.com/vmware/harbor/dao/base.go:98 +0x5db
ui_1       | main.main()
ui_1       |    /go/src/github.com/vmware/harbor/ui/main.go:69 +0x3c

**Comment by reasonerjt** [comment]
Will it?  depends on shoudl only ensure the status of depended container ,but not the actual service running in the container.

**Comment by hainingzhang** [comment]
No activity for a long time. Closing it for now. Please reopen if needed.
