### ISSUE TITLE
compose.service.NoSuchImage error running docker-compose up

### ISSUE THREAD

**Issue by pcgeek86** [vmware/harbor#581]
# Docker Engine

```
Server version: swarm/1.1.0
Server API version: 1.22
Go version (server): go1.5.3
Git commit (server): a0fd82b
OS/Arch (server): linux/amd64
```

# Docker Compose 

```
docker-compose version 1.8.0-rc2, build c72c966
```

# Issue

When I run `docker-compose up -d` I'm getting the following output / error

```
Pulling registry (library/registry:2.4.0)...
swarm-agent-3D55F3B3000000: Pulling library/registry:2.4.0... : downloaded
Pulling proxy (library/nginx:1.9)...
swarm-agent-3D55F3B3000000: Pulling library/nginx:1.9... : downloaded
deploy_log_1 is up-to-date
deploy_mysql_1 is up-to-date
deploy_ui_1 is up-to-date
deploy_jobservice_1 is up-to-date
Pulling registry (library/registry:2.4.0)...
swarm-agent-3D55F3B3000000: Pulling library/registry:2.4.0... : downloaded

ERROR: for registry  Image 'library/registry:2.4.0' not found
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 60, in main
  File "compose/cli/main.py", line 111, in perform_command
  File "compose/cli/main.py", line 814, in up
  File "compose/project.py", line 398, in up
  File "compose/parallel.py", line 60, in parallel_execute
compose.service.NoSuchImageError: Image 'library/registry:2.4.0' not found
docker-compose returned -1
```

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by reasonerjt** [comment]
Deployment on swarm is not tested, do you see the same issue when deploying on the stand alone docker daemon?

**Comment by pcgeek86** [comment]
@reasonerjt We've abandoned the Docker Swarm cluster for now, and just built up a stand-alone Docker Host running Ubuntu 16.04 Xenial Xerus LTS. We're not seeing the same problem thus far, but ran into another issue. I'll close this issue as "unsupported on Swarm."
