### ISSUE TITLE
Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use

### ISSUE THREAD

**Issue by cormachogan** [vmware/harbor#604]
docker-compose up fails as follows when trying to deploy harbor on Photon OS (full distro):

```
#####
root@harbor-photon [ /workspace/harbor/Deploy ]# ./prepare 
Clearing the configuration file: ./config/ui/app.conf
Clearing the configuration file: ./config/ui/env
Clearing the configuration file: ./config/registry/config.yml
Clearing the configuration file: ./config/db/env
Clearing the configuration file: ./config/jobservice/env
Generated configuration file: ./config/ui/env
Generated configuration file: ./config/ui/app.conf
Generated configuration file: ./config/registry/config.yml
Generated configuration file: ./config/db/env
Generated configuration file: ./config/jobservice/env
Clearing the configuration file: ./config/ui/private_key.pem
Clearing the configuration file: ./config/registry/root.crt
Generated configuration file: ./config/ui/private_key.pem
Generated configuration file: ./config/registry/root.crt
The configuration files are ready, please use docker-compose to start the service.
root@harbor-photon [ /workspace/harbor/Deploy ]# docker-compose up -d
Removing deploy_proxy_1
deploy_log_1 is up-to-date
deploy_registry_1 is up-to-date
deploy_mysql_1 is up-to-date
Recreating deploy_ui_1
Recreating 3fa9a3506faf_deploy_proxy_1
Recreating deploy_jobservice_1

ERROR: for proxy  driver failed programming external connectivity on endpoint deploy_proxy_1 (0d440744b58f701bfe85657bd17a8bbe3fe455574a21494dfee793ea5d79b17e): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 63, in main
AttributeError: 'ProjectError' object has no attribute 'msg'
docker-compose returned -1
root@harbor-photon [ /workspace/harbor/Deploy ]# 
```

If you are reporting a problem, please make sure the following information are provided:

1)Version of docker engine and docker-compose

```
root@harbor-photon [ /workspace/harbor/Deploy ]# docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64

root@harbor-photon [ /workspace/harbor/Deploy ]# docker-compose version
docker-compose version 1.7.1, build 0a9ab35
docker-py version: 1.8.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
root@harbor-photon [ /workspace/harbor/Deploy ]# 
```

2)Config files of harbor, you can get them by packaging "Deploy/config" directory

[config.tar.gz](https://github.com/vmware/harbor/files/388104/config.tar.gz)

3)Log files, you can get them by package the /var/log/harbor/ 
[
logs.tar.gz](https://github.com/vmware/harbor/files/388105/logs.tar.gz)

**Comment by reasonerjt** [comment]
Haven't tried on photon.
But it looks like there's some process listening to port 80 before you start harbor.

**Comment by cormachogan** [comment]
I was following the step here: http://www.vmtocloud.com/how-to-install-an-enterprise-docker-registry-on-photon-os-with-harbor/

But I'll check. Thanks

**Comment by cormachogan** [comment]
OK - so for some reason, the full ISO deployment of Photon OS already had httpd running. This was a brand new install of Photon OS. To resolve, I simply ran "service httpd stop", then re-ran the deploy and docker-compose, and it succeeded.

So I'm good now. Not sure if we want to add a pre-check for this, so I'll leave this open for the moment.
