### ISSUE TITLE
UI failed to connect to db, retry after 2 seconds... / Bad Gateway

### ISSUE THREAD

**Issue by AlexZeitler** [vmware/harbor#79]
I pulled 864b814 (to test #49 and #59), then `cd Deploy`, changed `hostname = localhost` in `harbor.cfg`.
Then I ran `docker-compose up -d` 

Wenn I open `http://localhost` I get a nginx `502 Bad Gateway` error.

The last few lines of `/var/log/harbor/<date>/docker_ui.log` look like this:

`12:41:10 failed to connect to db, retry after 2 seconds...`

After a few seconds, `deploy_ui` container is stopping completely.

**Comment by wknet123** [comment]
You need set  IP address as eth0 of your host due to containers need to discover each other when running up.

**Comment by AlexZeitler** [comment]
@wknet123 I thought this has been changed by 864b814. Please refer to #59 and #48 (https://github.com/vmware/harbor/issues/48#issuecomment-202829306).

**Comment by wknet123** [comment]
@AlexZeitler I still think that you changed hostname = localhost is not a property set.

**Comment by reasonerjt** [comment]
@AlexZeitler the PR #76  is for enabling the registry instance to call webhook via ui directly, and it is still suggested to set the attribute "hostname"with IP in harbor.cfg

However, I try to set "hostname" as local host, re-run the "prepare" script and "docker-compose up", I didn't see your issue.  The ui instance can be started and I don't see 502 error from nginx.

What version of docker are you using?

**Comment by AlexZeitler** [comment]
@reasonerjt I'm running on Docker version `1.10.3` and docker-compose version `1.6.2`.

**Comment by AlexZeitler** [comment]
@reasonerjt I just entered the IP address of `eth0` of the host in `harbor.cfg` for `localhost`, re-ran `prepare` followed by `docker-compose kill && docker-compose rm -f && docker-compose up -d` - the issue remains.

**Comment by AlexZeitler** [comment]
@reasonerjt This is the `docker_mysql.log`:

```
Apr  2 22:10:29 ubuntu docker/mysql[1841]: 2016-04-02 20:10:29 0 [Note] mysqld (mysqld 5.6.29) starting as process 1 ...
Apr  2 22:10:29 ubuntu docker/mysql[1841]: 2016-04-02 20:10:29 1 [Note] Plugin 'FEDERATED' is disabled.
Apr  2 22:10:29 ubuntu docker/mysql[1841]: 2016-04-02 20:10:29 1 [Note] InnoDB: Using atomics to ref count buffer pool pages
Apr  2 22:10:29 ubuntu docker/mysql[1841]: 2016-04-02 20:10:29 1 [Note] InnoDB: The InnoDB memory heap is disabled
Apr  2 22:10:29 ubuntu docker/mysql[1841]: 2016-04-02 20:10:29 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
Apr  2 22:10:29 ubuntu docker/mysql[1841]: 2016-04-02 20:10:29 1 [Note] InnoDB: Memory barrier is not used
Apr  2 22:10:29 ubuntu docker/mysql[1841]: 2016-04-02 20:10:29 1 [Note] InnoDB: Compressed tables use zlib 1.2.8
Apr  2 22:10:29 ubuntu docker/mysql[1841]: 2016-04-02 20:10:29 1 [Note] InnoDB: Using Linux native AIO
Apr  2 22:10:29 ubuntu docker/mysql[1841]: 2016-04-02 20:10:29 1 [Note] InnoDB: Using CPU crc32 instructions
Apr  2 22:10:29 ubuntu docker/mysql[1841]: 2016-04-02 20:10:29 1 [Note] InnoDB: Initializing buffer pool, size = 128.0M
Apr  2 22:10:30 ubuntu docker/mysql[1841]: 2016-04-02 20:10:30 1 [Note] InnoDB: Completed initialization of buffer pool
Apr  2 22:10:30 ubuntu docker/mysql[1841]: 2016-04-02 20:10:30 1 [Note] InnoDB: Highest supported file format is Barracuda.
Apr  2 22:10:30 ubuntu docker/mysql[1841]: 2016-04-02 20:10:30 1 [Note] InnoDB: The log sequence numbers 1741920 and 1741920 in ibdata files do not match the log sequence number 1741930 in the ib_logfiles!
Apr  2 22:10:30 ubuntu docker/mysql[1841]: 2016-04-02 20:10:30 1 [Note] InnoDB: Database was not shutdown normally!
Apr  2 22:10:30 ubuntu docker/mysql[1841]: 2016-04-02 20:10:30 1 [Note] InnoDB: Starting crash recovery.
Apr  2 22:10:30 ubuntu docker/mysql[1841]: 2016-04-02 20:10:30 1 [Note] InnoDB: Reading tablespace information from the .ibd files...
Apr  2 22:10:30 ubuntu docker/mysql[1841]: 2016-04-02 20:10:30 1 [Note] InnoDB: Restoring possible half-written data pages 
Apr  2 22:10:30 ubuntu docker/mysql[1841]: 2016-04-02 20:10:30 1 [Note] InnoDB: from the doublewrite buffer...
Apr  2 22:10:30 ubuntu docker/mysql[1841]: 2016-04-02 20:10:30 1 [Note] InnoDB: 128 rollback segment(s) are active.
Apr  2 22:10:30 ubuntu docker/mysql[1841]: 2016-04-02 20:10:30 1 [Note] InnoDB: Waiting for purge to start
Apr  2 22:10:30 ubuntu docker/mysql[1841]: 2016-04-02 20:10:30 1 [Note] InnoDB: 5.6.29 started; log sequence number 1741930
Apr  2 22:10:30 ubuntu docker/mysql[1841]: 2016-04-02 20:10:30 1 [Note] Server hostname (bind-address): '*'; port: 3306
Apr  2 22:10:30 ubuntu docker/mysql[1841]: 2016-04-02 20:10:30 1 [Note] IPv6 is available.
Apr  2 22:10:30 ubuntu docker/mysql[1841]: 2016-04-02 20:10:30 1 [Note]   - '::' resolves to '::';
Apr  2 22:10:30 ubuntu docker/mysql[1841]: 2016-04-02 20:10:30 1 [Note] Server socket created on IP: '::'.
Apr  2 22:10:30 ubuntu docker/mysql[1841]: 2016-04-02 20:10:30 1 [Warning] 'proxies_priv' entry '@ root@2cdaf725b895' ignored in --skip-name-resolve mode.
Apr  2 22:10:30 ubuntu docker/mysql[1841]: 2016-04-02 20:10:30 1 [Note] Event Scheduler: Loaded 0 events
Apr  2 22:10:30 ubuntu docker/mysql[1841]: 2016-04-02 20:10:30 1 [Note] mysqld: ready for connections.
Apr  2 22:10:30 ubuntu docker/mysql[1841]: Version: '5.6.29'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)

```

**Comment by wknet123** [comment]
Hi @AlexZeitler, how's it going?

**Comment by AlexZeitler** [comment]
@wknet123 thanks for asking - no progress so far.

**Comment by wknet123** [comment]
We updated codes and configurations recently, I recommend you to pull the latest repositories and rebuild images to check if the problem be resolved.

**Comment by AlexZeitler** [comment]
Thanks, will try it.

**Comment by AlexZeitler** [comment]
@wknet123 Pulled the latest version, set `hostname` in `harbor.cfg` to result of `ifconfig eth0`, ran `prepare` followed by `docker-compose up -d` - result:

```
Apr  7 16:21:32 ubuntu docker/ui[1860]: 2016/04/07 14:21:32 failed to connect to db, retry after 2 seconds...
Apr  7 16:21:34 ubuntu docker/ui[1860]: 2016/04/07 14:21:34 failed to connect to db, retry after 2 seconds...
Apr  7 16:21:36 ubuntu docker/ui[1860]: 2016/04/07 14:21:36 failed to connect to db, retry after 2 seconds...
Apr  7 16:21:38 ubuntu docker/ui[1860]: 2016/04/07 14:21:38 failed to connect to db, retry after 2 seconds...
Apr  7 16:21:40 ubuntu docker/ui[1860]: 2016/04/07 14:21:40 failed to connect to db, retry after 2 seconds...
Apr  7 16:21:42 ubuntu docker/ui[1860]: 2016/04/07 14:21:42 failed to connect to db, retry after 2 seconds...
Apr  7 16:21:44 ubuntu docker/ui[1860]: 2016/04/07 14:21:44 failed to connect to db, retry after 2 seconds...
Apr  7 16:21:46 ubuntu docker/ui[1860]: 2016/04/07 14:21:46 failed to connect to db, retry after 2 seconds...
Apr  7 16:21:48 ubuntu docker/ui[1860]: 2016/04/07 14:21:48 failed to connect to db, retry after 2 seconds...
Apr  7 16:21:50 ubuntu docker/ui[1860]: 2016/04/07 14:21:50 failed to connect to db, retry after 2 seconds...
Apr  7 16:21:52 ubuntu docker/ui[1860]: 2016/04/07 14:21:52 failed to connect to db, retry after 2 seconds...
```

**Comment by AlexZeitler** [comment]
Here's the output of `docker_mysql.log`:

```
Apr  7 16:19:42 ubuntu docker/mysql[1860]: 2016-04-07 14:19:42 0 [Note] mysqld (mysqld 5.6.29) starting as process 1 ...
Apr  7 16:19:42 ubuntu docker/mysql[1860]: 2016-04-07 14:19:42 1 [Note] Plugin 'FEDERATED' is disabled.
Apr  7 16:19:42 ubuntu docker/mysql[1860]: 2016-04-07 14:19:42 1 [Note] InnoDB: Using atomics to ref count buffer pool pages
Apr  7 16:19:42 ubuntu docker/mysql[1860]: 2016-04-07 14:19:42 1 [Note] InnoDB: The InnoDB memory heap is disabled
Apr  7 16:19:42 ubuntu docker/mysql[1860]: 2016-04-07 14:19:42 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
Apr  7 16:19:42 ubuntu docker/mysql[1860]: 2016-04-07 14:19:42 1 [Note] InnoDB: Memory barrier is not used
Apr  7 16:19:42 ubuntu docker/mysql[1860]: 2016-04-07 14:19:42 1 [Note] InnoDB: Compressed tables use zlib 1.2.8
Apr  7 16:19:42 ubuntu docker/mysql[1860]: 2016-04-07 14:19:42 1 [Note] InnoDB: Using Linux native AIO
Apr  7 16:19:42 ubuntu docker/mysql[1860]: 2016-04-07 14:19:42 1 [Note] InnoDB: Using CPU crc32 instructions
Apr  7 16:19:42 ubuntu docker/mysql[1860]: 2016-04-07 14:19:42 1 [Note] InnoDB: Initializing buffer pool, size = 128.0M
Apr  7 16:19:42 ubuntu docker/mysql[1860]: 2016-04-07 14:19:42 1 [Note] InnoDB: Completed initialization of buffer pool
Apr  7 16:19:43 ubuntu docker/mysql[1860]: 2016-04-07 14:19:43 1 [Note] InnoDB: Highest supported file format is Barracuda.
Apr  7 16:19:43 ubuntu docker/mysql[1860]: 2016-04-07 14:19:43 1 [Note] InnoDB: 128 rollback segment(s) are active.
Apr  7 16:19:43 ubuntu docker/mysql[1860]: 2016-04-07 14:19:43 1 [Note] InnoDB: Waiting for purge to start
Apr  7 16:19:43 ubuntu docker/mysql[1860]: 2016-04-07 14:19:43 1 [Note] InnoDB: 5.6.29 started; log sequence number 1741940
Apr  7 16:19:43 ubuntu docker/mysql[1860]: 2016-04-07 14:19:43 1 [Note] Server hostname (bind-address): '*'; port: 3306
Apr  7 16:19:43 ubuntu docker/mysql[1860]: 2016-04-07 14:19:43 1 [Note] IPv6 is available.
Apr  7 16:19:43 ubuntu docker/mysql[1860]: 2016-04-07 14:19:43 1 [Note]   - '::' resolves to '::';
Apr  7 16:19:43 ubuntu docker/mysql[1860]: 2016-04-07 14:19:43 1 [Note] Server socket created on IP: '::'.
Apr  7 16:19:43 ubuntu docker/mysql[1860]: 2016-04-07 14:19:43 1 [Warning] 'proxies_priv' entry '@ root@2cdaf725b895' ignored in --skip-name-resolve mode.
Apr  7 16:19:43 ubuntu docker/mysql[1860]: 2016-04-07 14:19:43 1 [Note] Event Scheduler: Loaded 0 events
Apr  7 16:19:43 ubuntu docker/mysql[1860]: 2016-04-07 14:19:43 1 [Note] mysqld: ready for connections.
Apr  7 16:19:43 ubuntu docker/mysql[1860]: Version: '5.6.29'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 0 [Note] mysqld (mysqld 5.6.29) starting as process 1 ...
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] Plugin 'FEDERATED' is disabled.
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] InnoDB: Using atomics to ref count buffer pool pages
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] InnoDB: The InnoDB memory heap is disabled
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] InnoDB: Memory barrier is not used
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] InnoDB: Compressed tables use zlib 1.2.8
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] InnoDB: Using Linux native AIO
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] InnoDB: Using CPU crc32 instructions
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] InnoDB: Initializing buffer pool, size = 128.0M
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] InnoDB: Completed initialization of buffer pool
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] InnoDB: Highest supported file format is Barracuda.
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] InnoDB: The log sequence numbers 1741940 and 1741940 in ibdata files do not match the log sequence number 1741950 in the ib_logfiles!
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] InnoDB: Database was not shutdown normally!
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] InnoDB: Starting crash recovery.
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] InnoDB: Reading tablespace information from the .ibd files...
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] InnoDB: Restoring possible half-written data pages 
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] InnoDB: from the doublewrite buffer...
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] InnoDB: 128 rollback segment(s) are active.
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] InnoDB: Waiting for purge to start
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] InnoDB: 5.6.29 started; log sequence number 1741950
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] Server hostname (bind-address): '*'; port: 3306
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] IPv6 is available.
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note]   - '::' resolves to '::';
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] Server socket created on IP: '::'.
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Warning] 'proxies_priv' entry '@ root@2cdaf725b895' ignored in --skip-name-resolve mode.
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] Event Scheduler: Loaded 0 events
Apr  7 16:20:25 ubuntu docker/mysql[1860]: 2016-04-07 14:20:25 1 [Note] mysqld: ready for connections.
Apr  7 16:20:25 ubuntu docker/mysql[1860]: Version: '5.6.29'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
```

**Comment by AlexZeitler** [comment]
After a while, `docker_ui.log` has been updated and the container exited:

```
Apr  7 16:21:58 ubuntu docker/ui[1860]: panic: Failed to connect to DB after 60 seconds
Apr  7 16:21:58 ubuntu docker/ui[1860]: 
Apr  7 16:21:58 ubuntu docker/ui[1860]: goroutine 1 [running]:
Apr  7 16:21:58 ubuntu docker/ui[1860]: github.com/vmware/harbor/dao.InitDB()
Apr  7 16:21:58 ubuntu docker/ui[1860]: #011/go/src/github.com/vmware/harbor/dao/base.go:99 +0x4c8
Apr  7 16:21:58 ubuntu docker/ui[1860]: main.main()
Apr  7 16:21:58 ubuntu docker/ui[1860]: #011/go/src/github.com/vmware/harbor/main.go:70 +0x40
Apr  7 16:21:58 ubuntu docker/ui[1860]: 
Apr  7 16:21:58 ubuntu docker/ui[1860]: goroutine 17 [syscall, locked to thread]:
Apr  7 16:21:58 ubuntu docker/ui[1860]: runtime.goexit()
Apr  7 16:21:58 ubuntu docker/ui[1860]: #011/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
Apr  7 16:21:58 ubuntu docker/ui[1860]: 
Apr  7 16:21:58 ubuntu docker/ui[1860]: goroutine 5 [syscall]:
Apr  7 16:21:58 ubuntu docker/ui[1860]: os/signal.loop()
Apr  7 16:21:58 ubuntu docker/ui[1860]: #011/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
Apr  7 16:21:58 ubuntu docker/ui[1860]: created by os/signal.init.1
Apr  7 16:21:58 ubuntu docker/ui[1860]: #011/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
Apr  7 16:21:58 ubuntu docker/ui[1860]: 
Apr  7 16:21:58 ubuntu docker/ui[1860]: goroutine 6 [chan receive]:
Apr  7 16:21:58 ubuntu docker/ui[1860]: github.com/vmware/harbor/vendor/github.com/astaxie/beego/cache.(*MemoryCache).vaccuum(0xc820102690)
Apr  7 16:21:58 ubuntu docker/ui[1860]: #011/go/src/github.com/vmware/harbor/vendor/github.com/astaxie/beego/cache/memory.go:216 +0x71
Apr  7 16:21:58 ubuntu docker/ui[1860]: created by github.com/vmware/harbor/vendor/github.com/astaxie/beego/cache.(*MemoryCache).StartAndGC
Apr  7 16:21:58 ubuntu docker/ui[1860]: #011/go/src/github.com/vmware/harbor/vendor/github.com/astaxie/beego/cache/memory.go:206 +0x25c
Apr  7 16:21:58 ubuntu docker/ui[1860]: 
Apr  7 16:21:58 ubuntu docker/ui[1860]: goroutine 7 [sleep]:
Apr  7 16:21:58 ubuntu docker/ui[1860]: time.Sleep(0x77359400)
Apr  7 16:21:58 ubuntu docker/ui[1860]: #011/usr/local/go/src/runtime/time.go:59 +0xf9
Apr  7 16:21:58 ubuntu docker/ui[1860]: github.com/vmware/harbor/dao.InitDB.func1(0xc82000a02b, 0x5, 0x0, 0x0, 0xc820280a10)
Apr  7 16:21:58 ubuntu docker/ui[1860]: #011/go/src/github.com/vmware/harbor/dao/base.go:92 +0x157
Apr  7 16:21:58 ubuntu docker/ui[1860]: created by github.com/vmware/harbor/dao.InitDB
Apr  7 16:21:58 ubuntu docker/ui[1860]: #011/go/src/github.com/vmware/harbor/dao/base.go:95 +0x310
```

**Comment by wknet123** [comment]
Did you remove the last left volume named '/data' before run up?

**Comment by AlexZeitler** [comment]
No. Removed it now, but got the same result.

**Comment by wknet123** [comment]
Which version is your Go?

**Comment by AlexZeitler** [comment]
On the host? (because in the container it should be the expected one)

**Comment by AlexZeitler** [comment]
The version in the `deploy_ui` container is `go version go1.5.1 linux/amd64`

**Comment by wknet123** [comment]
It seems that the UI does not connect to the DB, can I have a look at your current UI env under the 'Deploy/config/ui'

**Comment by AlexZeitler** [comment]
Here we go:

```
MYSQL_HOST=mysql
MYSQL_PORT=3306
MYSQL_USR=root
MYSQL_PWD=root123
REGISTRY_URL=http://registry:5000
CONFIG_PATH=/etc/ui/app.conf
HARBOR_REG_URL=192.168.21.142
HARBOR_ADMIN_PASSWORD=Harbor12345
HARBOR_URL=http://192.168.21.142
AUTH_MODE=db_auth
LDAP_URL=ldaps://ldap.mydomain.com
LDAP_BASE_DN=uid=%s,ou=people,dc=mydomain,dc=com
SELF_REGISTRATION=on
LOG_LEVEL=debug
```

**Comment by wknet123** [comment]
Make sure that port 80 or 3306 does not be occupied by other services?

**Comment by AlexZeitler** [comment]
`netstat -lpn |grep :80` and `netstat -lpn |grep :3306` with containers stopped didn't return anything.

Starting the containers, `netstat -lpn |grep :80` returned:
```
tcp6       0      0 :::80                   :::*                    LISTEN      24649/docker-proxy
```

**Comment by wknet123** [comment]
Did you see logs in docker_ui.log as below,
`Apr  8 00:03:31 docker/ui[2041]: 2016-04-07T16:03:31Z [INFO] Config path: /etc/ui/app.conf
Apr  8 00:03:31 docker/ui[2041]: 2016-04-07T16:03:31Z [DEBUG] [base.go:73]: db url: mysql:3306, db user: root`

**Comment by AlexZeitler** [comment]
That's the complete `docker_ui.log` starting after `docker-compose up -d` until `deploy_ui` has stopped:

```
Apr  7 18:17:38 ubuntu docker/ui[1860]: 2016/04/07 16:17:38 Config path: /etc/ui/app.conf
Apr  7 18:17:38 ubuntu docker/ui[1860]: 2016/04/07 16:17:38 failed to connect to db, retry after 2 seconds...
Apr  7 18:17:40 ubuntu docker/ui[1860]: 2016/04/07 16:17:40 failed to connect to db, retry after 2 seconds...
Apr  7 18:17:42 ubuntu docker/ui[1860]: 2016/04/07 16:17:42 failed to connect to db, retry after 2 seconds...
Apr  7 18:17:44 ubuntu docker/ui[1860]: 2016/04/07 16:17:44 failed to connect to db, retry after 2 seconds...
Apr  7 18:17:46 ubuntu docker/ui[1860]: 2016/04/07 16:17:46 failed to connect to db, retry after 2 seconds...
Apr  7 18:17:48 ubuntu docker/ui[1860]: 2016/04/07 16:17:48 failed to connect to db, retry after 2 seconds...
Apr  7 18:17:50 ubuntu docker/ui[1860]: 2016/04/07 16:17:50 failed to connect to db, retry after 2 seconds...
Apr  7 18:17:52 ubuntu docker/ui[1860]: 2016/04/07 16:17:52 failed to connect to db, retry after 2 seconds...
Apr  7 18:17:54 ubuntu docker/ui[1860]: 2016/04/07 16:17:54 failed to connect to db, retry after 2 seconds...
Apr  7 18:17:56 ubuntu docker/ui[1860]: 2016/04/07 16:17:56 failed to connect to db, retry after 2 seconds...
Apr  7 18:17:58 ubuntu docker/ui[1860]: 2016/04/07 16:17:58 failed to connect to db, retry after 2 seconds...
Apr  7 18:18:00 ubuntu docker/ui[1860]: 2016/04/07 16:18:00 failed to connect to db, retry after 2 seconds...
Apr  7 18:18:02 ubuntu docker/ui[1860]: 2016/04/07 16:18:02 failed to connect to db, retry after 2 seconds...
Apr  7 18:18:04 ubuntu docker/ui[1860]: 2016/04/07 16:18:04 failed to connect to db, retry after 2 seconds...
Apr  7 18:18:06 ubuntu docker/ui[1860]: 2016/04/07 16:18:06 failed to connect to db, retry after 2 seconds...
Apr  7 18:18:08 ubuntu docker/ui[1860]: 2016/04/07 16:18:08 failed to connect to db, retry after 2 seconds...
Apr  7 18:18:10 ubuntu docker/ui[1860]: 2016/04/07 16:18:10 failed to connect to db, retry after 2 seconds...
Apr  7 18:18:12 ubuntu docker/ui[1860]: 2016/04/07 16:18:12 failed to connect to db, retry after 2 seconds...
Apr  7 18:18:14 ubuntu docker/ui[1860]: 2016/04/07 16:18:14 failed to connect to db, retry after 2 seconds...
Apr  7 18:18:16 ubuntu docker/ui[1860]: 2016/04/07 16:18:16 failed to connect to db, retry after 2 seconds...
Apr  7 18:18:18 ubuntu docker/ui[1860]: 2016/04/07 16:18:18 failed to connect to db, retry after 2 seconds...
Apr  7 18:18:20 ubuntu docker/ui[1860]: 2016/04/07 16:18:20 failed to connect to db, retry after 2 seconds...
Apr  7 18:18:22 ubuntu docker/ui[1860]: 2016/04/07 16:18:22 failed to connect to db, retry after 2 seconds...
Apr  7 18:18:24 ubuntu docker/ui[1860]: 2016/04/07 16:18:24 failed to connect to db, retry after 2 seconds...
Apr  7 18:18:26 ubuntu docker/ui[1860]: 2016/04/07 16:18:26 failed to connect to db, retry after 2 seconds...
Apr  7 18:18:28 ubuntu docker/ui[1860]: 2016/04/07 16:18:28 failed to connect to db, retry after 2 seconds...
Apr  7 18:18:30 ubuntu docker/ui[1860]: 2016/04/07 16:18:30 failed to connect to db, retry after 2 seconds...
Apr  7 18:18:32 ubuntu docker/ui[1860]: 2016/04/07 16:18:32 failed to connect to db, retry after 2 seconds...
Apr  7 18:18:34 ubuntu docker/ui[1860]: 2016/04/07 16:18:34 failed to connect to db, retry after 2 seconds...
Apr  7 18:18:36 ubuntu docker/ui[1860]: 2016/04/07 16:18:36 failed to connect to db, retry after 2 seconds...
Apr  7 18:18:38 ubuntu docker/ui[1860]: panic: Failed to connect to DB after 60 seconds
Apr  7 18:18:38 ubuntu docker/ui[1860]: 
Apr  7 18:18:38 ubuntu docker/ui[1860]: goroutine 1 [running]:
Apr  7 18:18:38 ubuntu docker/ui[1860]: github.com/vmware/harbor/dao.InitDB()
Apr  7 18:18:38 ubuntu docker/ui[1860]: #011/go/src/github.com/vmware/harbor/dao/base.go:99 +0x4c8
Apr  7 18:18:38 ubuntu docker/ui[1860]: main.main()
Apr  7 18:18:38 ubuntu docker/ui[1860]: #011/go/src/github.com/vmware/harbor/main.go:70 +0x40
Apr  7 18:18:38 ubuntu docker/ui[1860]: 
Apr  7 18:18:38 ubuntu docker/ui[1860]: goroutine 17 [syscall, locked to thread]:
Apr  7 18:18:38 ubuntu docker/ui[1860]: runtime.goexit()
Apr  7 18:18:38 ubuntu docker/ui[1860]: #011/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
Apr  7 18:18:38 ubuntu docker/ui[1860]: 
Apr  7 18:18:38 ubuntu docker/ui[1860]: goroutine 5 [syscall]:
Apr  7 18:18:38 ubuntu docker/ui[1860]: os/signal.loop()
Apr  7 18:18:38 ubuntu docker/ui[1860]: #011/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
Apr  7 18:18:38 ubuntu docker/ui[1860]: created by os/signal.init.1
Apr  7 18:18:38 ubuntu docker/ui[1860]: #011/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
Apr  7 18:18:38 ubuntu docker/ui[1860]: 
Apr  7 18:18:38 ubuntu docker/ui[1860]: goroutine 6 [chan receive]:
Apr  7 18:18:38 ubuntu docker/ui[1860]: github.com/vmware/harbor/vendor/github.com/astaxie/beego/cache.(*MemoryCache).vaccuum(0xc820104690)
Apr  7 18:18:38 ubuntu docker/ui[1860]: #011/go/src/github.com/vmware/harbor/vendor/github.com/astaxie/beego/cache/memory.go:216 +0x71
Apr  7 18:18:38 ubuntu docker/ui[1860]: created by github.com/vmware/harbor/vendor/github.com/astaxie/beego/cache.(*MemoryCache).StartAndGC
Apr  7 18:18:38 ubuntu docker/ui[1860]: #011/go/src/github.com/vmware/harbor/vendor/github.com/astaxie/beego/cache/memory.go:206 +0x25c
Apr  7 18:18:38 ubuntu docker/ui[1860]: 
Apr  7 18:18:38 ubuntu docker/ui[1860]: goroutine 7 [sleep]:
Apr  7 18:18:38 ubuntu docker/ui[1860]: time.Sleep(0x77359400)
Apr  7 18:18:38 ubuntu docker/ui[1860]: #011/usr/local/go/src/runtime/time.go:59 +0xf9
Apr  7 18:18:38 ubuntu docker/ui[1860]: github.com/vmware/harbor/dao.InitDB.func1(0xc82000a02b, 0x5, 0x0, 0x0, 0xc820280a10)
Apr  7 18:18:38 ubuntu docker/ui[1860]: #011/go/src/github.com/vmware/harbor/dao/base.go:92 +0x157
Apr  7 18:18:38 ubuntu docker/ui[1860]: created by github.com/vmware/harbor/dao.InitDB
Apr  7 18:18:38 ubuntu docker/ui[1860]: #011/go/src/github.com/vmware/harbor/dao/base.go:95 +0x310
```

**Comment by wknet123** [comment]
Are you sure that you have executed `docker-compose build` since pulled the latest code?
It seems that the log format is different with me.

**Comment by AlexZeitler** [comment]
:scream: :scream: :scream: I totally forgot that, now I can access the site. Thanks @wknet123 for your patience!

But I cannot log in using `admin` / `Harbor12345`

**Comment by AlexZeitler** [comment]
`docker_ui.log`:

```
Apr  7 18:29:29 ubuntu docker/ui[1860]: 2016-04-07T16:29:29Z [ERROR] [main.go:72]: Failed to get user, userID: 1 Error 1054: Unknown column 'sysadmin_flag' in 'field list'
Apr  7 18:29:29 ubuntu docker/ui[1860]: 2016/04/07 16:29:29 #033[1;34m[asm_amd64.s:1696][I] http server Running on :80#033[0m
Apr  7 18:29:36 ubuntu docker/ui[1860]: 2016/04/07 16:29:36 #033[1;34m[router.go:828][D] | GET        | /                                        | 6.255881ms       | match      | /                                        | #033[0m
Apr  7 18:29:36 ubuntu docker/ui[1860]: 2016-04-07T16:29:36Z [WARNING] No user id in session, canceling request
Apr  7 18:31:21 ubuntu docker/ui[1860]: 2016/04/07 16:31:21 #033[1;34m[router.go:828][D] | GET        | /signIn                                  | 2.996691ms       | match      | /signIn                                  | #033[0m
Apr  7 18:31:21 ubuntu docker/ui[1860]: 2016-04-07T16:31:21Z [WARNING] No user id in session, canceling request
Apr  7 18:31:31 ubuntu docker/ui[1860]: 2016-04-07T16:31:31Z [DEBUG] [authenticator.go:52]: Current AUTH_MODE is db_auth
Apr  7 18:31:41 ubuntu docker/ui[1860]: 2016-04-07T16:31:41Z [DEBUG] [authenticator.go:52]: Current AUTH_MODE is db_auth
Apr  7 18:31:52 ubuntu docker/ui[1860]: 2016-04-07T16:31:52Z [DEBUG] [authenticator.go:52]: Current AUTH_MODE is db_auth
Apr  7 18:33:09 ubuntu docker/ui[1860]: 2016-04-07T16:33:09Z [DEBUG] [authenticator.go:52]: Current AUTH_MODE is db_auth
Apr  7 18:33:14 ubuntu docker/ui[1860]: 2016/04/07 16:33:14 #033[1;34m[router.go:828][D] | GET        | /signIn                                  | 2.847745ms       | match      | /signIn                                  | #033[0m
Apr  7 18:33:15 ubuntu docker/ui[1860]: 2016-04-07T16:33:15Z [WARNING] No user id in session, canceling request
Apr  7 18:33:57 ubuntu docker/ui[1860]: 2016/04/07 16:33:57 #033[1;34m[router.go:828][D] | GET        | /signIn                                  | 4.17547ms        | match      | /signIn                                  | #033[0m
Apr  7 18:33:58 ubuntu docker/ui[1860]: 2016-04-07T16:33:58Z [WARNING] No user id in session, canceling request
Apr  7 18:35:10 ubuntu docker/ui[1860]: 2016-04-07T16:35:10Z [DEBUG] [authenticator.go:52]: Current AUTH_MODE is db_auth
Apr  7 18:35:56 ubuntu docker/ui[1860]: 2016/04/07 16:35:56 #033[1;34m[router.go:828][D] | GET        | /forgotPassword                          | 2.403083ms       | match      | /forgotPassword                          | #033[0m
Apr  7 18:35:59 ubuntu docker/ui[1860]: 2016-04-07T16:35:59Z [WARNING] No user id in session, canceling request
```

**Comment by wknet123** [comment]
It seems that you should remove the older volume `/data` because we've updated the DB schema of this version.

**Comment by AlexZeitler** [comment]
Thanks again, this solved it!
