### ISSUE TITLE
problem about docker-compose v2

### ISSUE THREAD

**Issue by perhapszzy** [vmware/harbor#88]
I was able to start the dockers on v1 a few days ago, but after changing to v2, it can't connect to database:

```
Removing deploy_proxy_1
Starting deploy_log_1
Starting deploy_ui_1
Starting deploy_mysql_1
Starting deploy_registry_1
Recreating d0e168193174_d0e168193174_d0e168193174_d0e168193174_deploy_proxy_1
Attaching to deploy_log_1, deploy_ui_1, deploy_registry_1, deploy_mysql_1, deploy_proxy_1
ui_1        | 2016-04-06T15:09:54Z [INFO] Config path: /etc/ui/app.conf
registry_1  | time="2016-04-06T15:09:54.443001161Z" level=info msg="debug server listening localhost:5001" 
ui_1        | 2016-04-06T15:09:54Z [INFO] failed to connect to db, retry after 2 seconds...
registry_1  | time="2016-04-06T15:09:54.444358057Z" level=info msg="configuring endpoint harbor (http://ui/service/notifications), timeout=500ns, headers=map[]" go.version=go1.5.3 instance.id=0e9d47bc-ecdd-42ab-9404-7ce92e546174 service=registry version=v2.3.0 
ui_1        | 2016-04-06T15:09:56Z [INFO] failed to connect to db, retry after 2 seconds...
mysql_1     | 2016-04-06 15:09:54 0 [Note] mysqld (mysqld 5.6.29) starting as process 1 ...
registry_1  | time="2016-04-06T15:09:54.444443413Z" level=info msg="redis not configured" go.version=go1.5.3 instance.id=0e9d47bc-ecdd-42ab-9404-7ce92e546174 service=registry version=v2.3.0 
ui_1        | 2016-04-06T15:09:58Z [INFO] failed to connect to db, retry after 2 seconds...
registry_1  | time="2016-04-06T15:09:54.44537561Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.5.3 instance.id=0e9d47bc-ecdd-42ab-9404-7ce92e546174 service=registry version=v2.3.0 
ui_1        | 2016-04-06T15:10:00Z [INFO] failed to connect to db, retry after 2 seconds...
registry_1  | time="2016-04-06T15:09:54.445568058Z" level=debug msg="configured \"token\" access controller" go.version=go1.5.3 instance.id=0e9d47bc-ecdd-42ab-9404-7ce92e546174 service=registry version=v2.3.0 
registry_1  | time="2016-04-06T15:09:54.445635237Z" level=info msg="listening on [::]:5000" go.version=go1.5.3 instance.id=0e9d47bc-ecdd-42ab-9404-7ce92e546174 service=registry version=v2.3.0 
ui_1        | 2016-04-06T15:10:02Z [INFO] failed to connect to db, retry after 2 seconds...
mysql_1     | 2016-04-06 15:09:54 1 [Note] Plugin 'FEDERATED' is disabled.
ui_1        | 2016-04-06T15:10:04Z [INFO] failed to connect to db, retry after 2 seconds...
mysql_1     | 2016-04-06 15:09:54 1 [Note] InnoDB: Using atomics to ref count buffer pool pages
mysql_1     | 2016-04-06 15:09:54 1 [Note] InnoDB: The InnoDB memory heap is disabled
mysql_1     | 2016-04-06 15:09:54 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql_1     | 2016-04-06 15:09:54 1 [Note] InnoDB: Memory barrier is not used
mysql_1     | 2016-04-06 15:09:54 1 [Note] InnoDB: Compressed tables use zlib 1.2.8
mysql_1     | 2016-04-06 15:09:54 1 [Note] InnoDB: Using Linux native AIO
mysql_1     | 2016-04-06 15:09:54 1 [Note] InnoDB: Using CPU crc32 instructions
mysql_1     | 2016-04-06 15:09:54 1 [Note] InnoDB: Initializing buffer pool, size = 128.0M
mysql_1     | 2016-04-06 15:09:54 1 [Note] InnoDB: Completed initialization of buffer pool
mysql_1     | 2016-04-06 15:09:54 1 [Note] InnoDB: Highest supported file format is Barracuda.
mysql_1     | 2016-04-06 15:09:54 1 [Note] InnoDB: 128 rollback segment(s) are active.
mysql_1     | 2016-04-06 15:09:54 1 [Note] InnoDB: Waiting for purge to start
mysql_1     | 2016-04-06 15:09:54 1 [Note] InnoDB: 5.6.29 started; log sequence number 1701222
mysql_1     | 2016-04-06 15:09:54 1 [Note] Server hostname (bind-address): '*'; port: 3306
mysql_1     | 2016-04-06 15:09:54 1 [Note] IPv6 is available.
mysql_1     | 2016-04-06 15:09:54 1 [Note]   - '::' resolves to '::';
mysql_1     | 2016-04-06 15:09:54 1 [Note] Server socket created on IP: '::'.
mysql_1     | 2016-04-06 15:09:54 1 [Warning] 'proxies_priv' entry '@ root@3381ee0ee5ce' ignored in --skip-name-resolve mode.
mysql_1     | 2016-04-06 15:09:54 1 [Note] Event Scheduler: Loaded 0 events
mysql_1     | 2016-04-06 15:09:54 1 [Note] mysqld: ready for connections.
mysql_1     | Version: '5.6.29'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
ui_1        | 2016-04-06T15:10:06Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:08Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:10Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:12Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:14Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:16Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:18Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:20Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:22Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:24Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:26Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:28Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:30Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:32Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:34Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:36Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:38Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:40Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:42Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:44Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:46Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:48Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:50Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | 2016-04-06T15:10:52Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1        | panic: Failed to connect to DB after 60 seconds
ui_1        | 
ui_1        | goroutine 1 [running]:
ui_1        | github.com/vmware/harbor/dao.InitDB()
ui_1        | 	/go/src/github.com/vmware/harbor/dao/base.go:100 +0x4c8
ui_1        | main.main()
ui_1        | 	/go/src/github.com/vmware/harbor/main.go:70 +0x40
ui_1        | 
ui_1        | goroutine 17 [syscall, locked to thread]:
ui_1        | runtime.goexit()
ui_1        | 	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
ui_1        | 
ui_1        | goroutine 5 [syscall]:
ui_1        | os/signal.loop()
ui_1        | 	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
ui_1        | created by os/signal.init.1
ui_1        | 	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
ui_1        | 
ui_1        | goroutine 6 [chan receive]:
ui_1        | github.com/vmware/harbor/vendor/github.com/astaxie/beego/cache.(*MemoryCache).vaccuum(0xc8200f2660)
ui_1        | 	/go/src/github.com/vmware/harbor/vendor/github.com/astaxie/beego/cache/memory.go:216 +0x71
ui_1        | created by github.com/vmware/harbor/vendor/github.com/astaxie/beego/cache.(*MemoryCache).StartAndGC
ui_1        | 	/go/src/github.com/vmware/harbor/vendor/github.com/astaxie/beego/cache/memory.go:206 +0x25c
ui_1        | 
ui_1        | goroutine 7 [sleep]:
ui_1        | time.Sleep(0x77359400)
ui_1        | 	/usr/local/go/src/runtime/time.go:59 +0xf9
ui_1        | github.com/vmware/harbor/dao.InitDB.func1(0xc82000a02b, 0x5, 0x0, 0x0, 0xc820278a10)
ui_1        | 	/go/src/github.com/vmware/harbor/dao/base.go:93 +0x226
ui_1        | created by github.com/vmware/harbor/dao.InitDB
ui_1        | 	/go/src/github.com/vmware/harbor/dao/base.go:96 +0x310
deploy_ui_1 exited with code 2
```

I verified that my docker-compose version is 1.7.0:
```
docker-compose version 1.7.0rc1, build 1ad8866
docker-py version: 1.8.0-rc2
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```
and my docker version is 1.10.3:
```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
OS/Arch:      linux/amd64
```

**Comment by perhapszzy** [comment]
The images were built from an older version. The problem fixed by rebuild the images.
